
      FUNCTION TVEF1(A,B,C,D,RLT,R,PHI,DEC)
      RF=SQRT(1.+A*R+B*R*R)
      CSL=COS(RLT)
      CSX=-CSL*COS(DEC)*COS(PHI)+ZETA(RLT,DEC)
      CSX2=SQRT(ABS(CSX))
      XF=SIGN(CSX2,CSX)
      VUT=W(C,RLT,PHI,DEC)
      VDIUR=EXP(D*(XF-1.))
      TVEF1=RF*VDIUR*VUT
      RETURN
      END
