<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Apple macOS version 5.6.0">
<title>Radar Observations</title>
<link rel="stylesheet" type="text/css" href=
"../../../docs/html/doc.css">
<link href="../../../docs/images/dart.ico" rel="shortcut icon">
</head>
<body>
<a name="TOP" id="TOP"></a>
<h1>Radar Observations</h1>
<table border="0" summary="" cellpadding="5">
<tr>
<td valign="middle"><img src="../../../docs/images/Dartboard7.png"
alt="DART project logo" height="70"></td>
<td>Jump to <a href="../../../docs/index.html">DART Documentation
Main Index</a></td>
</tr>
</table>
<a href="#DataSources">DATA SOURCES</a> / <a href=
"#Programs">PROGRAMS</a> / <a href="#Modules">MODULES</a> /
<a href="#Namelist">NAMELIST</a> / <a href="#Errors">ERRORS</a> /
<a href="#FuturePlans">FUTURE PLANS</a> / <a href="#Legalese">TERMS
OF USE</a>
<h2>Overview</h2>
<p>Several programs for converting radar observations into DART
obs_seq format exist, and will be placed in this directory when
they are ready for distribution. Observations generated by these
programs have been successfully assimilated with weather models in
the DART framework.</p>
<p>This directory currently contains a program for generating
synthetic radar observations for a <a href=
"http://en.wikipedia.org/wiki/WSR-88D">WSR-88D (NEXRAD)</a>. It can
generate reflectivity and/or doppler radial velocity observations
with clear-air or storm sweep patterns, for testing or for OSSEs
(Observing System Simulation Experiments).</p>
<p>There are challenges to working with radar data; for more
information contact us.</p>
<!--==================================================================-->
<a name="DataSources" id="DataSources"></a>
<hr>
<h2>DATA SOURCES</h2>
<p> </p>
<!--==================================================================-->
<a name="Programs" id="Programs"></a>
<hr>
<h2>PROGRAMS</h2>
<p><em class="code">create_obs_radar_sequence</em> generates one or
more sets of synthetic radar observations. Change into the
<em class="code">work</em> subdirectory and run <em class=
"code">quickbuild.csh</em> to build this program.</p>
<p>Many DART users working with radar observations are using the
WRF Weather and Research Forecast model. See the <a href=
"../../../models/wrf/regression/Radar/README">WRF tests
directory</a> for pointers to data to run a radar test case.</p>
<p>In addition to the programs available in the DART distribution,
the following external program produces DART observation sequence
files:</p>
<ul>
<li><a href="http://code.google.com/p/opaws/">Observation
Processing And Wind Synthesis (OPAWS)</a>: OPAWS can process NCAR
Dorade (sweep) and NCAR EOL Foray (netcdf) radar data. It analyzes
(grids) data in either two-dimensions (on the conical surface of
each sweep) or three-dimensions (Cartesian). Analyses are output in
netcdf, Vis5d, and/or DART (Data Assimilation Research Testbed)
formats.</li>
</ul>
<!--==================================================================-->
<!-- Describe the bugs.                                               -->
<!--==================================================================-->
<a name="KnownBugs" id="KnownBugs"></a>
<hr>
<h2>KNOWN BUGS</h2>
<p>none</p>
<!--==================================================================-->
<!-- Describe Future Plans.                                           -->
<!--==================================================================-->
<a name="FuturePlans" id="FuturePlans"></a>
<hr>
<h2>FUTURE PLANS</h2>
<p>none</p>
<!--==================================================================-->
<!-- Legalese & Metadata                                              -->
<!--==================================================================-->
<a name="Legalese" id="Legalese"></a>
<hr>
<h2>Terms of Use</h2>
<p>DART software - Copyright UCAR. This open source software is
provided by UCAR, "as is", without charge, subject to all terms of
use at <a href=
"http://www.image.ucar.edu/DAReS/DART/DART_download">http://www.image.ucar.edu/DAReS/DART/DART_download</a></p>
<!--==================================================================-->
</body>
</html>
