
      SUBROUTINE AMPHZ(F,IR)
C     CONVERTS COMPLEX SOLUTION TO (AMP,PHASE) WHERE PHASE IS TIME OF MA
      COMMON /MODEi/NZONAL,MOIS,NSS
      COMMON /MODEr/PERIOD,FREQ,FLUX
      REAL LAMDA,MPI
      COMPLEX F(*)
      
      pi=acos(-1.)
      mpi=-1.*pi
      tpi=2.*pi

      DO 1 I=1,IR
      Y=AIMAG(F(I))
      X=REAL(F(I))+1.0E-08
      LAMDA=-ATAN2(Y,X)/FLOAT(NZONAL)
      IF(LAMDA.LT.MPI) GO TO 2
      IF(LAMDA.GT.PI) GO TO 3
      GO TO 4
2     LAMDA=LAMDA+TPI
      GO TO 4
3     LAMDA=LAMDA-TPI
4     PHASE=(1.+LAMDA/PI)*12.
      AMP=CABS(F(I))
1     F(I)=CMPLX(AMP,PHASE)
      RETURN
      END
