      SUBROUTINE CONV(XX,Z)
C    CONVERTS STRETCHED VAR. (X) TO ALTITUDE (Z)
      COMMON/HTVECT/XV(501),ZV(501)
      DIMENSION S1(3),S2(3)
C    TABLE SELECTION OF FOUR INTERPOLATING POINTS AROUND X
      CALL ATSM(XX,XV,ZV,501,1,S1,S2,3)
C    PERFORM AITKEN-LAGRANGE INTERPOLATION
      CALL ALI(XX,S1,S2,Z,3,1.0E-06,IER)
      RETURN
      END
