 obs_sequence
obs_kind_definitions
           1
           1 RAW_STATE_VARIABLE              
  num_copies:            2  num_qc:            1
  num_obs:          2  max_num_obs:            2
observations                                                                                                                     
truth                                                                                                                            
Quality Control                                                                                                                  
  first:            1  last:        2
 OBS            1
   2.33136633410425     
   3.47889361011565     
   0.00000000000000     
          -1           2          -1
obdef
loc1d
  0.390042510120342     
kind
           1
  3600          0
   1.00000000000000     
 OBS            2
   4.40993275557209     
   4.79362930462177     
   0.00000000000000     
           1           -1          -1
obdef
loc1d
  0.171148413632676     
kind
           1
  3600          0
   1.00000000000000     
