#!/bin/csh 
#
# The following directories are not needed for the distribution.
#
# Keyword check follows:
#
# $Date: 2007-01-23 21:38:37 -0700 (Tue, 23 Jan 2007) $
# $Revision: 2565 $
# $Author: thoar $
# $HeadURL: http://subversion.ucar.edu/DAReS/DART/trunk/shell_scripts/DART_distribution_prune $
# $Id: DART_distribution_prune 2565 2007-01-24 04:38:37Z thoar $
# $Source$
#
# That would be too cool if it worked.

set SNAME = $0

if ( ! -d DART ) then
   echo "$SNAME:t must be run from ABOVE the top-level"
   echo "DART directory -- please try again."
   exit 1
endif

foreach DIRECTORY ( chisq  \
   xxxxxxxxxxxxxxxxxxxxxxx \
   models/forced_barot     \
   models/gswm             \
   models/null_model       \
   models/oned_wave        \
   models/oscillator       \
   models/rose             \
   ncep_obs/bufr_lib       \
   qc                      \
   system_simulation )

   echo "Removing $DIRECTORY from the DART distribution."
   \rm -rf DART/$DIRECTORY

end
