#!/bin/csh 
#
# The following directories are not needed for the distribution.
#
# Keyword check follows:
#
# $Date$
# $Revision$
# $Author$
# $HeadURL$
# $Id$
# $Source$
#
# That would be too cool if it worked.

set SNAME = $0

if ( ! -d DART ) then
   echo "$SNAME:t must be run from ABOVE the top-level"
   echo "DART directory -- please try again."
   exit 1
endif

foreach DIRECTORY ( chisq  \
   nothing \
   models/forced_barot     \
   models/GSWM             \
   models/null_model       \
   models/oned_wave        \
   models/oscillator       \
   models/rose             \
   ncep_obs/bufr_lib       \
   browntrout              \
   system_simulation )

   echo "Removing $DIRECTORY from the DART distribution."
   \rm -rf DART/$DIRECTORY

end
