#!/bin/csh
#
# Data Assimilation Research Testbed -- DART
# Copyright 2004, Data Assimilation Initiative, University Corporation for Atmospheric Research
# Licensed under the GPL -- www.gpl.org/licenses/gpl.html
#
# $Id$
#
../../../mkmf/mkmf -p trans_date_to_dart -t ../../../mkmf/mkmf.template -c "-Duse_netCDF" \
 -a "../../.." path_names_trans_date_to_dart
