#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../build_templates/mkmf -p fill_inflation_restart \
 -t  ../../../build_templates/mkmf.template \
 -a "../../.." path_names_fill_inflation_restart

exit $status

