#!/bin/csh
#
# DART software - Copyright 2004 - 2013 UCAR. This open source software is
# provided by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id$


../../../mkmf/mkmf -p test_sizes -t ../../../mkmf/mkmf.template   \
        -a "../../.." path_names_test_sizes

exit $status
