<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Apple macOS version 5.6.0">
<title>module reg_factor_mod</title>
<link rel="stylesheet" type="text/css" href=
"../../../docs/html/doc.css">
<link href="../../../docs/images/dart.ico" rel="shortcut icon">
</head>
<body>
<a name="TOP" id="TOP"></a>
<h1>MODULE reg_factor</h1>
<table border="0" summary="" cellpadding="5">
<tr>
<td valign="middle"><img src="../../../docs/images/Dartboard7.png"
alt="DART project logo" height="70"></td>
<td>Jump to <a href="../../../docs/index.html">DART Documentation
Main Index</a></td>
</tr>
</table>
<a href="#Interface">INTERFACES</a> / <a href=
"#Namelist">NAMELIST</a> / <a href="#FilesUsed">FILES</a> /
<a href="#References">REFERENCES</a> / <a href="#Errors">ERRORS</a>
/ <a href="#FuturePlans">PLANS</a> / <a href=
"#PrivateComponents">PRIVATE COMPONENTS</a> / <a href=
"#Legalese">TERMS OF USE</a>
<h2>Overview</h2>
<p>Computes a weighting factor to reduce the impact of observations
on state variables using information from groups of ensembles. Can
be run using groups or using archived summary information available
from previous group filter experiments.</p>
<!--==================================================================-->
<a name="OtherModulesUsed" id="OtherModulesUsed"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>OTHER MODULES USED</h2>
<pre>
types_mod
utilities_mod
time_manager_mod
</pre>
<!--==================================================================-->
<!-- Declare all public entities ...                                  -->
<!-- duplicate public routines template as many times as necessary    -->
<!-- make sure you replace all yyyroutine?? strings                   -->
<!--==================================================================-->
<!--Note to authors. The first row of the table is different.         -->
<!--==================================================================-->
<a name="Interface" id="Interface"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>PUBLIC INTERFACES</h2>
<table>
<tr>
<td><em class="call">use reg_factor_mod, only :</em></td>
<td><a href="#comp_reg_factor">comp_reg_factor</a></td>
</tr>
</table>
<p>A note about documentation style. Optional arguments are
enclosed in brackets <em class="optionalcode">[like this]</em>.</p>
<!--===================== DESCRIPTION OF A ROUTINE =====================-->
<a name="comp_reg_factor" id="comp_reg_factor"></a><br>
<div class="routine"><em class="call">var =
comp_reg_factor(num_groups, regress, obs_index, state_index
<em class=
"optionalcode">[, obs_state_ind] [, obs_state_max]</em>)</em>
<pre>
real(r8)                                    :: <em class=
"code"> comp_reg_factor </em>
integer,                         intent(in) :: <em class=
"code"> num_groups </em>
real(r8), dimension(num_groups), intent(in) :: <em class=
"code"> regress </em>
integer,                         intent(in) :: <em class=
"code"> obs_index </em>
integer,                         intent(in) :: <em class=
"code"> state_index </em>
integer, optional,               intent(in) :: <em class=
"optionalcode"> obs_state_ind </em>
integer, optional,               intent(in) :: <em class=
"optionalcode"> obs_state_max </em>
</pre></div>
<div class="indent1"><!-- Description -->
<p>Returns a weighting factor given regression factors from each
group of a group filter or retrieves a factor generated by previous
group filter runs from a file.</p>
<table width="100%" border="0" summary="" cellpadding="3">
<tr>
<td valign="top"><em class="code">num_groups   </em></td>
<td>Number of groups. Set to 1 when using information from
previously run group filter from file.</td>
</tr>
<tr>
<td valign="top"><em class="code">regress   </em></td>
<td>Regression factor from each group for a given state variable
and observation variable pair.</td>
</tr>
<tr>
<td valign="top"><em class="code">obs_index   </em></td>
<td>Integer index of the observation being processed. Not used in
current implementation .</td>
</tr>
<tr>
<td valign="top"><em class="code">state_index
  </em></td>
<td>Integer index of state variable being processed. Not used in
current implementation.</td>
</tr>
<tr>
<td valign="top"><em class="optionalcode">obs_state_ind
  </em></td>
<td>Index into file generated for Bgrid model which could be
duplicated in other large models.</td>
</tr>
<tr>
<td valign="top"><em class="optionalcode">obs_state_max
  </em></td>
<td>Maximum number of observation state variable pairs with
non-zero impacts for a given model and observation sequence. Used
for generating Bgrid statistic files.</td>
</tr>
</table>
</div>
<br>
<!--==================================================================-->
<!--=================== DESCRIPTION OF A NAMELIST  ===================-->
<!--==================================================================-->
 <a name="Namelist" id="Namelist"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>NAMELIST</h2>
<p>This namelist is read from the file <em class=
"file">input.nml</em>. Namelists start with an ampersand '&amp;'
and terminate with a slash '/'. Character strings that contain a
'/' must be enclosed in quotes to prevent them from prematurely
terminating the namelist.</p>
<div class="namelist">
<pre>
&amp;reg_factor_nml
   select_regression    = 1,
   input_reg_file       = "time_mean_reg",
   save_reg_diagnostics = .false.,
   reg_diagnostics_file = "reg_diagnostics"  
/
</pre></div>
<br>
<br>
<div>
<table border="0" cellpadding="10" width="100%" summary=
'namelist description'>
<thead align="left">
<tr>
<th>Item</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody valign="top">
<tr>
<td>select_regression</td>
<td>integer</td>
<td>Selects the method for computing regression factor.
<ul style="list-style: none;">
<li>1 = compute using sampling theory for any ensemble size.</li>
<li>2 = low order model format. Works from archived time mean or
time median regression files generated by low-order models like
Lorenz-96.</li>
<li>3 = selects bgrid archived file. This is not currently
supported in released versions.</li>
</ul>
</td>
</tr>
<tr>
<td>input_reg_file</td>
<td>character(len=129)</td>
<td>File name from which statistics are to be read for
select_regression = 3.</td>
</tr>
<tr>
<td>save_reg_diagnostics</td>
<td>logical<em class="unit"> </em></td>
<td>True if regression diagnostics should be computed.</td>
</tr>
<tr>
<td>reg_diagnostics_file</td>
<td>character(len=129)<em class="unit"> </em></td>
<td>File name to which to write diagnostics.</td>
</tr>
</tbody>
</table>
</div>
<br>
<br>
<!--==================================================================-->
<!-- Describe the Files Used by this module.                          -->
<!--==================================================================-->
 <a name="FilesUsed" id="FilesUsed"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>FILES</h2>
<ul>
<li>(optional) input regression file from namelist variable
input_reg_file.</li>
<li>reg_factor_mod.nml in input.nml</li>
</ul>
<table border="0">
<tr>
<th align="left">filename</th>
<th align="left">purpose</th>
</tr>
<tr>
<td>from <em class=
"file">input.nml</em>&amp;reg_factor_mod:input_reg_file</td>
<td>file of regression coefficients</td>
</tr>
</table>
<!--==================================================================-->
<!-- Cite references, if need be.                                     -->
<!--==================================================================-->
<a name="References" id="References"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>REFERENCES</h2>
<ul>
<li>none</li>
</ul>
<!--==================================================================-->
<!-- Describe all the error conditions and codes.                     -->
<!--==================================================================-->
<a name="Errors" id="Errors"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>ERROR CODES and CONDITIONS</h2>
<div class="errors">
<table border="1" cellspacing="1" cellpadding="10" width="100%">
<tr>
<th>Routine</th>
<th>Message</th>
<th>Comment</th>
</tr>
<tr><!-- routine -->
<td valign="top">comp_reg_factor</td>
<!-- message -->
<td valign="top">Illegal value for namelist parameter
select_regression</td>
<!-- comment -->
<td valign="top">Value must be 1(sampling theory), 2 (table lookup)
or 3 (read from obs_state_reg_file).</td>
</tr>
</table>
</div>
<h2>KNOWN BUGS</h2>
<p>none at this time</p>
<!--==================================================================-->
<!-- Describe Future Plans.                                           -->
<!--==================================================================-->
<a name="FuturePlans" id="FuturePlans"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>FUTURE PLANS</h2>
<p>none at this time</p>
<!--==================================================================-->
<!-- PrivateComponents                                                -->
<!--==================================================================-->
<a name="PrivateComponents" id="PrivateComponents"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>PRIVATE COMPONENTS</h2>
<p>N/A</p>
<!--==================================================================-->
<!-- Legalese & Metadata                                              -->
<!--==================================================================-->
<a name="Legalese" id="Legalese"></a>
<div class="top">[<a href="#">top</a>]</div>
<hr>
<h2>Terms of Use</h2>
<p>DART software - Copyright UCAR. This open source software is
provided by UCAR, "as is", without charge, subject to all terms of
use at <a href=
"http://www.image.ucar.edu/DAReS/DART/DART_download">http://www.image.ucar.edu/DAReS/DART/DART_download</a></p>
<!--==================================================================-->
</body>
</html>
