#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

# many times, the HDF libs and the NETCDF libs are in the same place ...

set    HDFDIR = ${NETCDF}
set    HDFDIR = /Users/thoar/intel_19.0.3
set HDFINCDIR = "-I${HDFDIR}/include"
set HDFLIBDIR = "-L${HDFDIR}/lib"
set   HDFLIBS = "-lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran"

../../../../build_templates/mkmf -p SMAP_L2_to_obs -t ../../../../build_templates/mkmf.template \
 -l "${HDFINCDIR} ${HDFLIBDIR} ${HDFLIBS}" \
 -a "../../../.." path_names_SMAP_L2_to_obs

exit $status

