#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

../../../../build_templates/mkmf -p ascii_table_converter -t ../../../../build_templates/mkmf.template \
 -a "../../../.." path_names_ascii_table_converter

exit $status

