#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

# these env vars seem to be defined on cheyenne by loading the hdf-eos module:
set MYINCDIR = "-I$NCAR_INC_HDFEOS"
set MYLIBDIR = "-L$NCAR_LIBS_HDFEOS"
set MYLIBS   = "$NCAR_LIBS_HDFEOS"

../../../../build_templates/mkmf -p convert_airs_rad_L2 -t ../../../../build_templates/mkmf.template \
 -l "${MYINCDIR} ${MYLIBDIR} ${MYLIBS}" \
 -a "../../../.." path_names_convert_airs_L2

exit $status

