#!/bin/sh

# set this
if [ $# -gt 0 ]; then
 yr=$1
else
 echo usage: $0 YYYY
 exit 0
fi


pre=obs_seq${yr}

let m=1
while [[ $m -le 12 ]]; do

  mm=`printf %02d $m`
  
  if [[ `ls ${pre}${mm}* 2>/dev/null | wc -l` -gt 0 ]]; then
     echo ${pre}${mm}

     echo -n $mm " 00  "; ls -1 ${pre}${mm}??00 2>/dev/null | wc -l
     echo -n $mm " 06  "; ls -1 ${pre}${mm}??06 2>/dev/null | wc -l
     echo -n $mm " 12  "; ls -1 ${pre}${mm}??12 2>/dev/null | wc -l
     echo -n $mm " 18  "; ls -1 ${pre}${mm}??18 2>/dev/null | wc -l
     echo ''
  fi
 
  let m=m+1
done

exit 0

