
% crude script to compare the same month across years.

%% DART software - Copyright UCAR. This open source software is provided
% by UCAR, "as is", without charge, subject to all terms of use at
% http://www.image.ucar.edu/DAReS/DART/DART_download
%
% The obs_diag_output.nc files are archived in
% /glade/p/nsc/ncis0006/Reanalyses/f.e21.FHIST_BGC.f09_025.CAM6assim.011/ ...
%                esp/hist/YYYY-MM/Diags_NTrS_YYYY-MM.tgz
% /gpfs/csfs1/cisl/dares/Reanalyses/f.e21.FHIST_BGC.f09_025.CAM6assim.011/ ...
%                esp/hist/YYYY-MM/Diags_NTrS_YYYY-MM.tgz

% The first place they live is

DOUT_S_ROOT = '/glade/scratch/raeder/f.e21.FHIST_BGC.f09_025.CAM6assim.011/archive/esp/hist';

fnames = {'Diags_NTrS_2011-08/obs_diag_output.nc', ...
          'Diags_NTrS_2012-08/obs_diag_output.nc', ...
          'Diags_NTrS_2013-08/obs_diag_output.nc', ...
          'Diags_NTrS_2014-08/obs_diag_output.nc', ...
          'Diags_NTrS_2015-08/obs_diag_output.nc', ...
   'BadSST/Diags_NTrS_2016-08/obs_diag_output.nc', ...
           };

files = cell(length(fnames),1);
for i = 1:length(fnames)
   files{i,1} = sprintf('%s/%s',DOUT_S_ROOT,fnames{i});
end

titles = {'2011-08',
          '2012-08',
          '2013-08',
          '2014-08',
          '2015-08',
          '2016-08'};

obsnames = {  ...
        'ACARS_HORIZONTAL_WIND', ...
        'ACARS_TEMPERATURE', ...
        'ACARS_U_WIND_COMPONENT', ...
        'ACARS_V_WIND_COMPONENT', ...
        'AIRCRAFT_HORIZONTAL_WIND', ...
        'AIRCRAFT_TEMPERATURE', ...
        'AIRCRAFT_U_WIND_COMPONENT', ...
        'AIRCRAFT_V_WIND_COMPONENT', ...
        'AIRS_SPECIFIC_HUMIDITY', ...
        'AIRS_TEMPERATURE', ...
        'GPSRO_REFRACTIVITY', ...
        'RADIOSONDE_HORIZONTAL_WIND', ...
        'RADIOSONDE_SPECIFIC_HUMIDITY', ...
        'RADIOSONDE_TEMPERATURE', ...
        'RADIOSONDE_U_WIND_COMPONENT', ...
        'RADIOSONDE_V_WIND_COMPONENT', ...
        'SAT_HORIZONTAL_WIND', ...
        'SAT_U_WIND_COMPONENT', ...
        'SAT_V_WIND_COMPONENT'};

copy = 'rmse';
prpo = 'prior';

figure; set(gcf,'Position',[  20, 500,625,900])
figure; set(gcf,'Position',[ 660, 500,625,900])
figure; set(gcf,'Position',[1300, 500,625,900])

compare_monthly_profiles(files,titles,obsnames,copy,prpo,'MarkerSize',5,'LineWidth',1.5);

