
      SUBROUTINE GEOGM(XLAT,XLONG,GMLAT,GMLONG)
C     THIS PROGRAM CONVERTS A POINT IN GEOGRAPHIC COORDINATES,
C     (XLAT,XLONG), INTO THE CORRESPONDING POINT IN GEOMAGNETIC
C     COORDINATES, (GMLAT,GMLONG). XLAT IS IN DEGREES NORTH (NEGATIVE IF
C     SOUTH). XLONG IS IN DEGREES EAST LONGITUDE (ALWAYS POSITIVE AND
C     LESS THAN 360).
      
      pi=acos(-1.)

      RFAC=PI/180.
      PLATR=78.5*RFAC
      PLONGR=291.*RFAC
      SPL=SIN(PLATR)
      CPL=COS(PLATR)
      RLAT=XLAT*RFAC
      RLONG=XLONG*RFAC
      SLM=SPL*SIN(RLAT)+CPL*COS(RLAT)*COS(PLONGR-RLONG)
      CLM=SQRT(1.-SLM**2)
      PHIM1=COS(RLAT)*SIN(RLONG-PLONGR)/CLM
      PHIM2=(SPL*SLM-SIN(RLAT))/(CPL*CLM)
      GMLAT=ASIN(SLM)/RFAC
      IF(PHIM1.GE.0..AND.PHIM2.GE.0.)GO TO 100
      IF(PHIM1.GE.0..AND.PHIM2.LT.0.)GO TO 101
      IF(PHIM1.LT.0..AND.PHIM2.LT.0.)GO TO 102
      IF(PHIM1.LT.0..AND.PHIM2.GE.0.)GO TO 103
      GO TO 110
  100 GMLONG=ASIN(PHIM1)/RFAC
      GO TO 104
  101 GMLONG=(PI-ABS(ASIN(PHIM1)))/RFAC
      GO TO 104
  102 GMLONG=(PI+ABS(ASIN(PHIM1)))/RFAC
      GO TO 104
  103 GMLONG=(2.*PI-ABS(ASIN(PHIM1)))/RFAC
  104 RETURN
  110 WRITE(7,111)
  111 FORMAT(1H ,12H ANGLE ERROR)
      STOP
      END
