      SUBROUTINE SOL(ALP,BET,FNC,FNC1,IR,IC)

c  Version 2.0 created by J. Forbes 2/3/91
c  Mod 2/6/91

      COMPLEX ALP(IR,IC),BET(IR),FNC(IR),FNC1(IR)
      CALL MPRDDV(ALP,FNC1,FNC,IR,IC)
      CALL GMADDV(FNC,BET,FNC,IR,1.)
      RETURN
      END
