#!/bin/csh
#
# Data Assimilation Research Testbed -- DART
# Copyright 2004, Data Assimilation Initiative, University Corporation for Atmospheric Research
# Licensed under the GPL -- www.gpl.org/licenses/gpl.html
#
../../../mkmf/mkmf -p update_wrf_bc -t ../../../mkmf/mkmf.template -c"-Duse_netCDF -DIFC80" \
 -a "../../.." path_names_update_wrf_bc
