#!/bin/tcsh

#----------------------------------------------------------------------
#### LSF options for BSUB
### -J      job name    (master script job.csh presumes filter.xxxx.log)
### -o      output listing filename 
### -P      account number
### -q      queue
### -n      number of tasks (processors)
### -x      exclusive use of node
### -R "span[ptile=(num procs you want on each node)]"
#
#BSUB -J filter
#BSUB -o f.log
#BSUB -e f.err
#BSUB -q regular
#BSUB -n 32

echo ""
mpirun.lsf ./filter

