#!/bin/tcsh
#
# Data Assimilation Research Testbed -- DART
# Copyright 2004-2006, Data Assimilation Research Section
# University Corporation for Atmospheric Research
# Licensed under the GPL -- www.gpl.org/licenses/gpl.html

# $Id$

#----------------------------------------------------------------------
#### LSF options for BSUB
### -J      job name    (master script job.csh presumes filter.xxxx.log)
### -o      output listing filename 
### -P      account number
### -q      queue
### -n      number of tasks (processors)
### -x      exclusive use of node
### -R "span[ptile=(num procs you want on each node)]"
#
#BSUB -J ctest
#BSUB -o c.log
#BSUB -e c.err
#BSUB -q regular
#BSUB -n 2

echo ""
cd $HOME/dart/DART/doc/mpi
mpirun.lsf ./ctest_mpi


