#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../../build_templates/mkmf -p convert_goes_ABI_L1b \
  -t ../../../../build_templates/mkmf.template \
 -a "../../../.." path_names_convert_goes_ABI_L1b

exit $status

