#!/bin/tcsh 
#

#BSUB -J filter
#BSUB -o filter.%J.log
#BSUB -q lrg_regular
#BSUB -n 32
#BSUB -P 93300315
#BSUB -W 0:30
#BSUB -R "span[ptile=32]"


ls -l filter
ldedit -btextpsize=64K -bdatapsize=64K -bstackpsize=64K filter

setenv TARGET_CPU_RANGE "-1"

mpirun.lsf /usr/local/bin/launch ./filter 


