#!/bin/csh -f
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id$

#*******************************************************************************
#
# ---------------------
# Purpose
# ---------------------
#
# This script gets 80 POP restart files from HPSS.
#*******************************************************************************

# Set Variables
setenv save_dir     POP_ensemble_dir
setenv save_path    /glade/scratch/${USER}/${save_dir}

# setenv start_year 31
setenv start_year 209
# setenv   end_year 201
setenv   end_year 270
# setenv  year_span 10
setenv  year_span 1
setenv  case_name g210.G_JRA.v14.gx1v7.01
setenv  hpss_path /home/whokim/csm/${case_name}/rest


mkdir -p ${save_path}
cd ${save_path}

@ iyear = $start_year

while ($iyear <= $end_year)
    
    # Zero pad the year string so that there are 4 digits
    if ($iyear < 10) then
        setenv zero_filled_year 000${iyear}
    else if ($iyear < 100) then
        setenv zero_filled_year 00${iyear}
    else if ($iyear < 1000) then
        setenv zero_filled_year 0${iyear}
    endif
   
    setenv  pop_filename ${case_name}.pop.r.${zero_filled_year}-01-01-00000.nc
    setenv  ovf_filename ${case_name}.pop.ro.${zero_filled_year}-01-01-00000
    setenv  cice_filename ${case_name}.cice.r.${zero_filled_year}-01-01-00000.nc
    
    setenv hpss_pop_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${pop_filename}
    setenv hpss_ovf_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${ovf_filename}
    setenv hpss_cice_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${cice_filename}
    
    echo "Getting file: ${pop_filename}"
    hsi cget ${pop_filename} : ${hpss_pop_filepath}
    
    echo "Getting file: ${ovf_filename}"
    hsi cget ${ovf_filename} : ${hpss_ovf_filepath}
    
    echo "Getting file: ${cice_filename}"
    hsi cget ${cice_filename} : ${hpss_cice_filepath}
    
    @ iyear += ${year_span}
end
