#!/bin/csh -f
#
# Copyright 2020 University Corporation for Atmospheric Research
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.
# Please view the License at http://www.apache.org/licenses/LICENSE-2.0
#
# ==============================================================================
# 
# ---------------------
# Purpose
# ---------------------
#
# This script gets POP restart files from HPSS and can be configured with 
# a start year, end year and a span.
#
# ==============================================================================

# Set Variables
setenv save_dir     POP_ensemble_dir
setenv save_path    /glade/scratch/${USER}/${save_dir}

# setenv start_year 31
setenv start_year 209
# setenv   end_year 201
setenv   end_year 270
# setenv  year_span 10
setenv  year_span 1
setenv  case_name g210.G_JRA.v14.gx1v7.01
setenv  hpss_path /home/whokim/csm/${case_name}/rest


mkdir -p ${save_path}
cd ${save_path}

@ iyear = $start_year

while ($iyear <= $end_year)
    
    # Zero pad the year string so that there are 4 digits
    setenv zero_filled_year = `printf %04d $iyear`
 
    setenv  pop_filename ${case_name}.pop.r.${zero_filled_year}-01-01-00000.nc
    setenv  ovf_filename ${case_name}.pop.ro.${zero_filled_year}-01-01-00000
    setenv  cice_filename ${case_name}.cice.r.${zero_filled_year}-01-01-00000.nc
    
    setenv hpss_pop_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${pop_filename}
    setenv hpss_ovf_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${ovf_filename}
    setenv hpss_cice_filepath ${hpss_path}/${zero_filled_year}-01-01-00000/${cice_filename}
    
    echo "Getting file: ${pop_filename}"
    hsi cget ${pop_filename} : ${hpss_pop_filepath}
    
    echo "Getting file: ${ovf_filename}"
    hsi cget ${ovf_filename} : ${hpss_ovf_filepath}
    
    echo "Getting file: ${cice_filename}"
    hsi cget ${cice_filename} : ${hpss_cice_filepath}
    
    @ iyear += ${year_span}
end
