
      SUBROUTINE AMPHZpw(F)
C     CONVERTS COMPLEX SOLUTION TO (AMP,PHASE) WHERE PHASE IS DEG.
      REAL LAMDA,MPI
      COMPLEX F(*)
      COMMON/MODE/NZONAL,PERIOD,FREQ,MOIS,NSS,FLUX
      DATA PI,MPI,TPI/3.14159,-3.14159,6.28318/
      DO 1 I=1,4
      Y=AIMAG(F(I))
      X=REAL(F(I))+1.0E-08
      LAMDA=-ATAN2(Y,X)
      IF(LAMDA.LT.MPI) GO TO 2
      IF(LAMDA.GT.PI) GO TO 3
      GO TO 4
2     LAMDA=LAMDA+TPI
      GO TO 4
3     LAMDA=LAMDA-TPI
4     PHASE=LAMDA*180./PI/float(nzonal)
      AMP=CABS(F(I))
1     F(I)=CMPLX(AMP,PHASE)
      RETURN
      END
