#!/bin/tcsh

#----------------------------------------------------------------------
#### LSF options for BSUB
### -J      job name    (master script job.csh presumes filter.xxxx.log)
### -o      output listing filename 
### -P      account number
### -q      queue
### -n      number of tasks (processors)
### -x      exclusive use of node
### -R "span[ptile=(num procs you want on each node)]"
#
#BSUB -J ftest
#BSUB -o f.log
#BSUB -e f.err
#BSUB -q regular
#BSUB -n 2

echo ""
cd $HOME/dart/DART/doc/mpi
mpirun.lsf ./ftest_mpi

