#!/bin/sh
#
# Data Assimilation Research Testbed -- DART
# Copyright 2004-2006, Data Assimilation Research Section
# University Corporation for Atmospheric Research
# Licensed under the GPL -- www.gpl.org/licenses/gpl.html

# $Id$

#----------------------------------------------------------------------
# directives to allow this to run as a batch jobs under PBS.
#PBS -N ct
#PBS -r n
#PBS -e ct.err
#PBS -o ct.log
#PBS -q small
#PBS -l nodes=5
#----------------------------------------------------------------------

echo ""
MPI_HOME=/usr/local/mpich-1.2.6-pgi-hpf-cc-5.2-4
echo setting MPI_HOME to $MPI_HOME

cd $HOME/dart/DART/doc/mpi
$MPI_HOME/bin/mpirun ./commtest

echo ""
echo 'done with script'

