#!/bin/csh
#
# Data Assimilation Research Testbed -- DART
# Copyright 2004, Data Assimilation Initiative, University Corporation for Atmospheric Research
# Licensed under the GPL -- www.gpl.org/licenses/gpl.html
#
../../mkmf/mkmf -p sampling_error -t ../../mkmf/mkmf.template -c"-Duse_netCDF" \
 -a "../.." path_names_sampling_error
