#!/bin/sh 

# this version counts daily gps files

# other versions can count prepqm, temp_obs, or
# cesm merged files.

if [ $# != 1 ]; then
  echo usage: $0 year
  exit 1
fi

yr=$1

# what's the fixed part of the prefix on these files?
# directory and non-date leading part of filename:

dir=../../GPS/local-complete2013
pre=obs_seq.gpsro_

let m=1
while [[ $m -le 12 ]]; do

  mm=`printf %02d $m`
  
  dname=${dir}/${yr}${mm}
  fname=${pre}${yr}${mm}
  tname=${dname}/${fname}
  if [[ `ls ${tname}* 2>/dev/null | wc -l` -gt 0 ]]; then
     echo ${yr}${mm} " " `ls -1 ${tname}* 2>/dev/null | wc -l`
  fi
 
  let m=m+1
done

exit 0

