# Makefile created by mkmf $Id$ 

include ../../../../build_templates/mkmf.template


.DEFAULT:
	-touch $@
all: fixsys preprocess
fixsys: 
	@ (cd ../../../../assimilation_code/modules/utilities; ./fixsystem $(FC) )
