<!--

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                   !!
!!                   GNU General Public License                      !!
!!                                                                   !!
!! This file is part of the Flexible Modeling System (FMS).          !!
!!                                                                   !!
!! FMS is free software; you can redistribute it and/or modify       !!
!! it and are expected to follow the terms of the GNU General Public !!
!! License as published by the Free Software Foundation.             !!
!!                                                                   !!
!! FMS is distributed in the hope that it will be useful,            !!
!! but WITHOUT ANY WARRANTY; without even the implied warranty of    !!
!! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     !!
!! GNU General Public License for more details.                      !!
!!                                                                   !!
!! You should have received a copy of the GNU General Public License !!
!! along with FMS; if not, write to:                                 !!
!!          Free Software Foundation, Inc.                           !!
!!          59 Temple Place, Suite 330                               !!
!!          Boston, MA  02111-1307  USA                              !!
!! or see:                                                           !!
!!          http://www.gnu.org/licenses/gpl.txt                      !!
!!                                                                   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-->
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Apple macOS version 5.6.0">
<title>module hs_forcing</title>
</head>
<body bgcolor="#AABBCC" text="#332211">
<div align="center"><font size="-2"><a href=
"#PUBLIC%20INTERFACE">PUBLIC INTERFACE</a> / <a href=
"#PUBLIC%20ROUTINES">ROUTINES</a> / <a href=
"#NAMELIST">NAMELIST</a> / <a href=
"#DIAGNOSTIC%20FIELDS">DIAGNOSTICS</a> / <a href=
"#ERROR%20MESSAGES">ERRORS</a> / <a href=
"#REFERENCES">REFERENCES</a> / <a href=
"#NOTES">NOTES</a></font><br>
<br></div>
<hr>
<h1>Module hs_forcing_mod</h1>
<a name="OVERVIEW" id="OVERVIEW">
<hr>
<h2>OVERVIEW</h2>
<!-- BEGIN OVERVIEW -->
<pre>

    Routines for computing heating and dissipation 
      for "Held-Suarez" benchmark integration of a dry GCM

</pre></a><!-- END OVERVIEW -->
<!--------------------------------------------------------------------->
 <a name="DESCRIPTION" id="DESCRIPTION"><!-- BEGIN DESCRIPTION -->
<pre>
</pre></a><!-- END DESCRIPTION -->
<!--------------------------------------------------------------------->
 <a name="OTHER MODULES USED">
<hr>
<h2>OTHER MODULES USED</h2>
<!-- BEGIN OTHER MODULES USED -->
<pre>

           fms_mod
     constants_mod
  time_manager_mod
  diag_manager_mod
 field_manager_mod
tracer_manager_mod

</pre></a><!-- END OTHER MODULES USED -->
<!--------------------------------------------------------------------->
 <a name="PUBLIC INTERFACE">
<hr>
<h2>PUBLIC INTERFACE</h2>
<!-- BEGIN PUBLIC INTERFACE -->
<pre>

  use hs_forcing_mod [,only: hs_forcing_init,   &
                             hs_forcing         ]

hs_forcing_init           : initializes module
hs_forcing                : adds tendencies to existing tendencies

<b>Notes:</b>

 Optional namelist input can be read from file input.nml.
 Diagnostic fields are specified in file diag_table.
 No restart files are needed or generated by this module.
 No data files are needed.

</pre></a><!-- END INTERFACE -->
<!--------------------------------------------------------------------->
 <a name="PUBLIC ROUTINES">
<hr>
<h2>PUBLIC ROUTINES</h2>
<!-- BEGIN PUBLIC ROUTINES -->
<pre>

<b>call hs_forcing_init</b> ( axes, Time )

 INPUT:

    axes -- integer, dimension(4)
        axis indices (x,y,zfull,zhalf) returned by module diag_manager_mod

    Time -- type(time_type)
        the current time


</pre>
<hr>
<pre>

<b>call hs_forcing</b> ( is, ie, js, je, dt, Time, lat, phalf, pfull,
                  u, v, t, r, um, vm, tm, rm, udt, vdt, tdt, rdt
                  <font color="#007700">[, mask, kbot]</font> )
    
 INPUT:  is, ie, js, je, dt, Time, lat, p_half, p_full, u, v, t, r

    is, ie, js, je -- integer, scalar
        global indices of the data window being passed

    dt -- real, scalar
        the time step (seconds)

    Time -- type(time_type)
        the current time

    lat -- real, dimension(:,:)
        latitudes of grid points in radians

    phalf -- real, dimension(:,:.:)
        half_level pressures (Pa)

    pfull -- real, dimension(:,:.:)
        full_level pressures (Pa)
        size(p_full,3) = size(p_half,3)-1

    u, v, t -- real, dimension(:,:.:)
        full level zonal wind (m/s), meridional wind(m/s), temperature (K), 
        size(u,3) = size(v,3) = size(t,3) = size(p_full,3)

    r -- real, dimension(:,:.:,:)
        full level tracers
        size(r,3) = size(p_full,3)
        size(r,4) = number of tracers

 IN/OUT:

    udt, vdt, tdt -- real, dimension(:,:,:)
       udt = du/dt = tendency of u (m/(s^2)), etc
       output has heating and friction added to input tendencies 

    rdt -- real, dimension(:,:.:,:)
       tendency of tracers


  OPTIONAL INPUT:  mask, kbot

    mask -- real, dimension(:,:,:)
       step-mountain/eta coordinate field mask

    kbot -- real, dimension(:,:)
       index of lowest model level (adjacent to step-mountain surface)
       
</pre></a><!-- END PUBLIC ROUTINES -->
<!--------------------------------------------------------------------->
 <a name="NAMELIST" id="NAMELIST">
<hr>
<h2>NAMELIST</h2>
<!-- BEGIN NAMELIST -->
<pre>

(all values listed are default values)   
(TE = radiative equilibrium -- see Held and Suarez)           

real    :: delh      =  60. (K) horizontal TE contrast from equator to pole 
real    :: t_zero    = 315. (K) TE at equator at surface
real    :: t_strat   = 200. (K) stratospheric temperature
real    :: delv      =  10. (K) parameter controling static stability of TE
real    :: eps       = 0.0  (K)  not in Held and Suarez (2*eps = TE difference
                                between NP and SP ( TE =&gt; TE + eps*sin(lat) )

damping times
units are (1/s) , value is inverse of damping time, if positive
          (days), value is damping time, if negative  

real    :: ka        =-40.0   radiative damping above the planetary boundary layer
real    :: ks        =-4.0    radiative damping within the planetary boundary layer
real    :: kf        =-1.0    frictional (Rayleigh) damping within the planetary boundary layer

real    :: sigma_b   = 0.7    top of planetary boundary layer in sigma coordinates

logical :: do_conserve_energy =.true.  if true, kinetic energy dissipated by friction
                                       is added to enthalpy, to conserve energy



   real :: trflux = 1.e-5   !  surface flux for optional tracer
   real :: trsink = -4.     !  damping time for tracer


</pre></a><!-- END NAMELIST -->
<!--------------------------------------------------------------------->
 <a name="DIAGNOSTIC FIELDS">
<hr>
<h2>DIAGNOSTIC FIELDS</h2>
<pre>
Diagnostic fields may be output to a netcdf file by specifying the 
module name identifier <b>hs_forcing</b> and the desired field names (given below)
in file <b>diag_table</b>. See the documentation for diag_manager.
</pre>
<!-- BEGIN DIAGNOSTIC FIELDS -->
<pre>

Diagnostic fields for module name identifier: <b>hs_forcing</b>

   field name       field description
   ----------       -----------------

   teq              equilibrium temperature (deg_K)
   tdt_ndamp        temperture tendency for newtonian damping (deg_K/sec)
   udt_rdamp        zonal wind tendency for rayleigh damping (m/s2)
   vdt_rdamp        meridional wind tendency for rayleigh damping (m/s2)
   tdt_diss_rdamp   Dissipative heating from Rayleigh damping (deg_K/sec)
   diss_heat_rdamp  Integrated dissipative heating for Rayleigh damping (W/m2)

<b>NOTES</b>

   1) Fields <b>tdt_diss_rdamp</b> and <b>diss_heat_rdamp</b> can only be output
      when namelist variable do_conserve_energy =.true.
   2) Field <b>teq</b> can be stored as packed data (valid range = 100,400).

</pre></a><!-- END DIAGNOSTIC FIELDS -->
<!--------------------------------------------------------------------->
 <a name="ERROR MESSAGES">
<hr>
<h2>ERROR MESSAGES</h2>
<!-- BEGIN ERROR MESSAGES -->
<pre>

<b>FATAL errors in hs_forcing_mod</b>

    <b>have not called hs_forcing_init</b>
        You have not called hs_forcing_init before hs_forcing.

</pre></a><!-- END ERROR MESSAGES -->
<!--------------------------------------------------------------------->
 <a name="REFERENCES" id="REFERENCES">
<hr>
<h2>REFERENCES</h2>
<!-- BEGIN REFERENCES -->
<pre>

Held, I. M., and M. J. Suarez, 1994: <b>A proposal for the intercomparison
of the dynamical cores of atmospheric general circulation models.</b> <i>Bulletin
of the American Meteorological Society,</i> <b>75(10)</b>, 1825-1830.

</pre></a><!-- END REFERENCES -->
<!--------------------------------------------------------------------->
 <a name="NOTES" id="NOTES">
<hr>
<h2>NOTES</h2>
<!-- BEGIN NOTES -->
<pre>

This module computes a source-sink term for all prognostic tracers.
The source term is a globally uniform surface flux given by namelist
variable trflux. The sink term is computed everywhere as coeff*tracer.
The default coefficient is given by namelist variable trsink.

The behavior of the source-sink term can also be controlled by 
field_table method "tracer_sms".
Examples:
           "tracer_sms", "NONE"
           "tracer_sms", "ON",  "flux=1.e-3,sink=-2."

</pre></a><!-- END NOTES -->
<!--------------------------------------------------------------------->
 <a name="FUTURE PLANS">
<hr>
<h2>FUTURE PLANS</h2>
<!-- BEGIN FUTURE PLANS -->
<pre>

    None.

</pre></a><!-- END FUTURE PLANS -->
<!--------------------------------------------------------------------->
<hr>
</body>
</html>
