#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# provided by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# ------------------------------------------------------------------------------

source DART_params_tower_assim.csh

# Prevent accidental removal of a previous case.
# If you want to replace the experiment, you have to manually
# remove the directories. 

if ( -e ${caseroot} ) then
   echo "WARNING"
   echo "WARNING : The CASE ${caseroot} already exists. Stopping."
   echo "WARNING : If you want to perform the experiment,"
   echo "WARNING : you have to manually remove the CASEROOT, EXEDIR, RUNDIR"
   echo "WARNING : or change the CASE name to something else."
   exit
endif

# ==============================================================================
#Search for -->CalLMIP settings<--- to see key changes 

setenv run_type      startup
setenv run_startdate ${startdate}
setenv run_queue main
setenv run_priority premium
setenv run_time 00:15:00

# the short-term archiver is turned off (initially?) to let you explore the
# run directory

setenv short_term_archiver off
setenv st_archive_queue main
setenv st_archive_time 00:05:00

# ==============================================================================
# Create the case - this creates the CASEROOT directory.
#

# FATAL idea to make caseroot the same dir as where this setup script is
# since the build process removes all files in the caseroot dir before
# populating it.  try to prevent shooting yourself in the foot.

if ( ${caseroot} == `pwd` ) then
   echo "ERROR: the setup script should not be located in the caseroot"
   echo "directory, because all files in the caseroot dir will be removed"
   echo "before creating the new case.  move the script to a safer place."
   exit 1
endif

echo "removing old files from ${caseroot}"
echo "removing old files from ${exeroot}"
echo "removing old files from ${rundir}"

${REMOVE} ${caseroot}
${REMOVE} ${exeroot}
${REMOVE} ${rundir}


echo " Starting create_newcase ..."


${cesmroot}/cime/scripts/create_newcase  --res  ${resolution} \
                                         --mach ${machine} \
                                         --compset ${compset} \
                                         --case ${caseroot} \
                                         --project ${project} \
                                         --run-unsupported \
                                         --ninst ${num_instances} \
                                         --multi-driver || exit 2



# ==============================================================================
# Preserve a copy of this script and the parameter file as it was run.
# Copy the DART setup script (CESM_DART_config) to CASEROOT.

set ThisFileName = $0:t
${COPY} $ThisFileName       ${caseroot}/${ThisFileName}.original
${COPY} DART_params_tower_assim.csh     ${caseroot}
${COPY} CESM_DART_config    ${caseroot}

# ==============================================================================
cd ${caseroot}
# ==============================================================================

# Save a copy for debug purposes
foreach FILE ( *xml )
   if ( ! -e          ${FILE}.original ) then
      ${COPY} ${FILE} ${FILE}.original
   endif
end

# Get a bunch of environment variables.
# If any of these are changed by xmlchange calls in this program,
# then they must be explicitly changed with setenv calls too.

setenv COMPSET               `./xmlquery COMPSET               --value` || exit 3
setenv COMP_ATM              `./xmlquery COMP_ATM              --value` || exit 3
setenv COMP_OCN              `./xmlquery COMP_OCN              --value` || exit 3
setenv CASEROOT              `./xmlquery CASEROOT              --value` || exit 3

# Make sure the case is configured with a stub ocean and a data atmosphere.

if ( (${COMP_OCN} != socn) || (${COMP_ATM} != datm) ) then
   echo " "
   echo "ERROR: This script is not appropriate for active ocean or atmospheric compsets."
   echo " "
   exit 3
endif

#CalLMIP settings
./xmlchange STOP_OPTION=${stop_option}
./xmlchange STOP_N=${stop_n}
./xmlchange RESUBMIT=${resubmit}
./xmlchange CALENDAR=${calendar}
#./xmlchange REST_OPTION=${stop_option}
#./xmlchange REST_N=${rest_n}

#CalLMIP settings
./xmlchange CLM_ACCELERATED_SPINUP=off
./xmlchange --force CLM_FORCE_COLDSTART=off
./xmlchange PLUMBER2SITE=DK-Sor
./xmlchange CLM_USRDAT_NAME=PLUMBER2
./xmlchange DATM_MODE=1PT
./xmlchange PTS_LON=11.64464
./xmlchange PTS_LAT=55.48587
./xmlchange DATM_YR_START_FILENAME=1997
# Hour 23
#./xmlchange START_TOD=82800
./xmlchange ATM_NCPL=48
# transient atm forcing
./xmlchange DATM_PRESAERO=SSP3-7.0
./xmlchange DATM_CO2_TSERIES=SSP3-7.0
./xmlchange DATM_PRESNDEP=SSP3-7.0


./xmlchange EXEROOT=${exeroot}
./xmlchange RUNDIR=${rundir}

# This comes from http://esmci.github.io/cime/data_models/data-atm.html
# "Note If DATM_MODE is set to CPLHIST, it is normally assumed that the model
# domain will be identical to all of the stream domains. To ensure this, the
# xml variables ATM_DOMAIN_PATH and ATM_DOMAIN_FILE are ignored and a valid
# setting must be given for DATM_CPLHIST_DOMAIN_FILE. If DATM_CPLHIST_DOMAIN_FILE
# is set to null, then the datm component domain information is read in from
# the first coupler history file in the target stream and it is assumed that the
# first coupler stream file that is pointed to contains the domain information
# for that stream. This is the default that should be used for this mode."

./xmlchange DATM_YR_ALIGN=${stream_year_align}
./xmlchange DATM_YR_START=${stream_year_first}
./xmlchange DATM_YR_END=${stream_year_last}

./xmlchange RUN_TYPE=${run_type}
./xmlchange RUN_STARTDATE=${run_startdate}
./xmlchange RUN_REFDATE=${run_startdate}


# pnetcdf is default

# CalLMIP settings
# Setting this for ensemble spin
# Loosening restrictions on MPITASKS
./xmlchange PIO_TYPENAME=pnetcdf
#./xmlchange MAX_MEM_PER_NODE=235
#./xmlchange MEM_PER_TASK=10 



# Only cap at 1 for single instance spin
# ./xmlchange MAX_MPITASKS_PER_NODE=1
# Task layout:
# Set the nodes_per_instance below to match your case.
# By computing task counts like we do below, we guarantee each instance uses
# a whole number of nodes which is the recommended configuration.
# CIME interprets a negative task count as representing the number of nodes.
# On Cheyenne (at least) using multiple threads is not recommended.

@ nthreads = ${number_of_threads}

## CalLMIP settings
## For site runs we just want 1 processor per instance (Get rid of -1)
## Can keep it this way for ensemble simulations
## This assigns each ensemble member to a single task within a single node

@ atm_tasks = ${nodes_per_instance}
@ cpl_tasks = ${nodes_per_instance}
@ ocn_tasks = ${nodes_per_instance}
@ wav_tasks = ${nodes_per_instance}
@ glc_tasks = ${nodes_per_instance}
@ ice_tasks = ${nodes_per_instance}
@ rof_tasks = ${nodes_per_instance}
@ lnd_tasks = ${nodes_per_instance}
@ esp_tasks = ${nodes_per_instance}

#If running 20 members or less with 1 node,  Just hardcode for ensemble using 1 node, and 1 processor per node
# Manually change the .case.run to this:
#PBS -l select=1:ncpus=20:mpiprocs=20:ompthreads=1:mem=235GB

# If running 80 members need to run on multiple nodes to increase memory,  
# Increase nodes, but cap tasks per node to distribute memory appropriately
# Manually change the .case.run to this:
#PBS -l select=4:ncpus=20:mpiprocs=20:ompthreads=1:mem=235GB


# These settings can be used for 20 or 80 members (instances)
./xmlchange ROOTPE_ATM=0,NTHRDS_ATM=$nthreads,NTASKS_ATM=$atm_tasks
./xmlchange ROOTPE_CPL=0,NTHRDS_CPL=$nthreads,NTASKS_CPL=$cpl_tasks
./xmlchange ROOTPE_OCN=0,NTHRDS_OCN=$nthreads,NTASKS_OCN=$ocn_tasks
./xmlchange ROOTPE_WAV=0,NTHRDS_WAV=$nthreads,NTASKS_WAV=$wav_tasks
./xmlchange ROOTPE_GLC=0,NTHRDS_GLC=$nthreads,NTASKS_GLC=$glc_tasks
./xmlchange ROOTPE_ICE=0,NTHRDS_ICE=$nthreads,NTASKS_ICE=$ice_tasks
./xmlchange ROOTPE_ROF=0,NTHRDS_ROF=$nthreads,NTASKS_ROF=$rof_tasks
./xmlchange ROOTPE_LND=0,NTHRDS_LND=$nthreads,NTASKS_LND=$lnd_tasks
./xmlchange ROOTPE_ESP=0,NTHRDS_ESP=$nthreads,NTASKS_ESP=$esp_tasks
./xmlchange MAX_MPITASKS_PER_NODE=20



./xmlchange  JOB_QUEUE=${run_queue}
./xmlchange  JOB_PRIORITY=${run_priority}
./xmlchange  JOB_WALLCLOCK_TIME=${run_time}

echo "setting up the case ... "

./case.setup --reset || exit 4

echo "case setup finished."

# ==============================================================================
# These are archiving options that may be used.

if (${short_term_archiver} == 'off') then
   ./xmlchange DOUT_S=FALSE
else
   ./xmlchange DOUT_S=TRUE
   ./xmlchange --subgroup case.st_archive --id JOB_QUEUE          --val ${st_archive_queue}
   ./xmlchange --subgroup case.st_archive --id JOB_WALLCLOCK_TIME --val ${st_archive_time}
endif

# DEBUG = TRUE implies turning on run and compile time debugging.
# INFO_DBUG level of debug output, 0=minimum, 1=normal, 2=more, 3=too much.

./xmlchange DEBUG=FALSE


# ==============================================================================
# Modify namelist templates for each instance.

@ inst = 1
while ( $inst <= $num_instances )

   if (${num_instances} == 1) then
      set inst_string = '' 
   else
      set inst_string = `printf _%04d $inst`
      set inst_string2 = `printf %04d $inst`
   endif
# ===========================================================================
# DATM namelist

   # ===========================================================================
   set fname = "user_nl_datm_streams${inst_string}"
   # ===========================================================================

   # Site Level Met Forcing

   #   set user_nl_datm_template        = user_nl_datm.CPLHISTForcing.complete
   #PLUMBER2.DK-Sor:datafiles=/glade/work/linnia/calLMIP/forcings/PLUMBER2_timefix/CTSM_DATM_DK-Sor_1997-2014.nc"
   #CalLMIP settings

   echo   "CLM_USRDAT.PLUMBER2:datavars = ZBOT     Sa_z, \ " >> ${fname}
   echo   "TBOT     Sa_tbot, \ "                             >> ${fname}
   echo   "QBOT     Sa_shum, \ "                             >> ${fname}
   echo   "WIND     Sa_wind, \ "                             >> ${fname}
   echo   "PRECTmms Faxa_precn, \ "                          >> ${fname}
   echo   "FSDS     Faxa_swdn, \ "                           >> ${fname}
   echo   "PSRF     Sa_pbot, \ "                             >> ${fname}
   echo   "FLDS     Faxa_lwdn "                              >> ${fname}
   
   # Met forcing years to cycle all years (1997-2014) This is set in previous xmlchange  calls
   echo "CLM_USRDAT.PLUMBER2:taxmode=cycle" >>    ${fname}
   echo "CLM_USRDAT.PLUMBER2:dtlimit=1e30"  >>    ${fname}
   echo "PLUMBER2.DK-Sor:taxmode=cycle"     >>    ${fname}
   # CHOOSE ONE
   # SINGLE INSTANCE MET FORCING
    echo "PLUMBER2.DK-Sor:datafiles=/glade/derecho/scratch/bmraczka/calLMIP/forcings/PLUMBER2_timefix/CTSM_DATM_DK-Sor_1997-2014.nc" >> ${fname}
   # PERTURBED MET FORCING
   # echo "PLUMBER2.DK-Sor:datafiles=/glade/derecho/scratch/bmraczka/calLMIP/forcings/DKSor_ensemble/DKSor_perturbed_final/${inst_string2}/CTSM_DATM_DK-Sor_2011-2014.ens${inst_string}.nc" >> ${fname}

   echo "PLUMBER2.DK-Sor:dtlimit=1e30" >>         ${fname}


   # Atm forcing years to match the transient years 1850-1997
   # All atm forcing years available through 1997, so extending not necessary
   echo "presaero.SSP3-7.0:year_first=1997" >>    ${fname} 
   echo "presaero.SSP3-7.0:year_last=2014" >>     ${fname} 
   echo "presaero.SSP3-7.0:year_align=1997" >>    ${fname}
   echo "presaero.SSP3-7.0:taxmode = extend" >>   ${fname}
   echo "presaero.SSP3-7.0:dtlimit=1e30" >>       ${fname}

   echo "presndep.SSP3-7.0:year_first=1997" >>    ${fname} 
   echo "presndep.SSP3-7.0:year_last=2014" >>     ${fname} 
   echo "presndep.SSP3-7.0:year_align=1997" >>    ${fname} 
   echo "presndep.SSP3-7.0:taxmode = extend" >>   ${fname}
   echo "presndep.SSP3-7.0:dtlimit=1e30" >>       ${fname}

   # This default co2 forcing file was causing errors, cannot detect 1850-1997 data -- it was resolved.
     echo "co2tseries.SSP3-7.0:datafiles=/glade/campaign/cesm/cesmdata/inputdata/atm/datm7/CO2/fco2_datm_globalSSP3-7.0_simyr_1750-2501_CMIP6_c201101.nc" >> ${fname}
   # echo "co2tseries.SSP3-7.0:datafiles=/glade/campaign/cesm/cesmdata/inputdata/atm/datm7/CO2/fco2_datm_globalSSP3-7.0_simyr_1750-2501_CMIP6_c201030.nc" >> ${fname}
   # echo "co2tseries.SSP3-7.0:datafiles=/glade/campaign/cesm/cesmdata/inputdata/atm/datm7/CO2/fco2_datm_global_simyr_1750-2014_CMIP6_c180929.nc" >> ${fname}   

   echo "co2tseries.SSP3-7.0:year_first=1997" >>  ${fname} 
   echo "co2tseries.SSP3-7.0:year_last=2014" >>   ${fname} 
   echo "co2tseries.SSP3-7.0:year_align=1997" >>  ${fname} 
   echo "co2tseries.SSP3-7.0:taxmode = extend" >> ${fname}
   echo "co2tseries.SSP3-7.0:dtlimit=1e30" >>     ${fname}

   # Surface Ozone data stream 

   echo "preso3.hist:year_first=1997" >>  ${fname}
   echo "preso3.hist:year_last=2014" >>   ${fname}
   echo "preso3.hist:year_align=1997" >>  ${fname}
   echo "preso3.hist:taxmode = extend" >> ${fname}
   echo "preso3.hist:dtlimit=1e30" >>     ${fname}



   # ===========================================================================
   set fname = "user_nl_clm${inst_string}"
   # ===========================================================================

   # This is the opportunity to output additional items at your own discretion.
   # may want to track the evolution of certain variables at different timescales.

   # hist_nhtfrq: Per tape series history write frequency.
   #              positive means in time steps 0=monthly negative means hours
   #              i.e. 5 means every 24 time-steps and -24 means every day
   #              Default: 0,-24,-24,-24,-24,-24
   # hist_mfilt:  Per tape series maximum number of time samples.

   echo "hist_empty_htapes = .true."              >> ${fname}
   # Excluded land use change for both transient and tower simulations
   echo "flanduse_timeseries = ''" >>            ${fname}
   #echo "flanduse_timeseries = '"/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata/surfdata.pftdyn_0.9x1.25_rcp8.5_simyr1850-2005_c130702.nc"'" >>            ${fname}
   #echo "flanduse_timeseries = '"/glade/derecho/scratch/bmraczka/CESM3_source/ctsm5.4.004/tools/site_and_regional/landuse.timeseries_Dk_Sor_hist_1850-2023_78pfts_c260202.nc"'" >>            ${fname}
   echo "fsurdat = '"/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/surfdata_esmf/PLUMBER2/ctsm5.3.0/surfdata_1x1_PLUMBER2_DK-Sor_hist_2000_16pfts_c240912.nc"'" >> ${fname}
   # The h0 and h1 sent to DART state for forward operator, h2 and h3 are diagnostics of  monthly and daiy averages for flux tower comparison
   # The h4 file is for met forcing timing and alignment diagnostics.
   echo "hist_mfilt = 1,1,12,3650"            >> ${fname}
   echo "hist_nhtfrq = -24,-24,0,-24"             >> ${fname}
   echo "hist_avgflag_pertape = 'A','A','A','A'" >> ${fname}
   echo "hist_dov2xy = .true.,.false.,.true.,.true." >> ${fname}
   echo "hist_fincl1 = 'LEAFC','TLAI','TOTSOMC_1m','NEP','FSH','EFLX_LH_TOT_R'" >> ${fname}
   echo "hist_fincl2 = 'TLAI'" >> ${fname} 
   echo "hist_fincl3 = 'TOTECOSYSC','TOTECOSYSN','TOTSOMC','TOTSOMN','TOTVEGC','DEADSTEMC','LIVESTEMC','LIVECROOTC','DEADCROOTC','FROOTC','TOTVEGN','CPOOL','TLAI','ELAI','GPP','ER','NPP','FSH','EFLX_LH_TOT_R','NEP','NBP','TWS','H2OSNO','H2OSOI','SOILLIQ','SOILWATER_10CM','TOTSOMC_1m','PCO2','TBOT','TOTSOMC','SOILC_vr'" >> ${fname}
   echo "hist_fincl4 = 'GPP','ER','NPP','FSH','EFLX_LH_TOT_R','NEP','NBP','FSDS','TWS','H2OSNO','H2OSOI','SOILLIQ','SOILWATER_10CM','BTRANMN','PCO2','TBOT','TLAI','ELAI','TOTSOMC','TOTSOMC_1m','SOILC_vr'" >> ${fname}
   # echo "hist_fincl5 = 'FSDS','FLDS','WIND','QBOT','TBOT','PBOT','RAIN_FROM_ATM','SNOW_FROM_ATM'" >> ${fname}
   # PARAMETER PERTURBATION OPTION
   #echo "paramfile= '"/glade/derecho/scratch/bmraczka/calLMIP/paramfiles/lhc${inst_string2}.nc"'" >> ${fname}
   echo "paramfile= '"/glade/work/bmraczka/calLMIP/lhc/paramfiles/calLMIP_precalibrated${inst_string2}.nc"'" >> ${fname}
   # METEOROLOGY PERTURBATION  OPTION
   #echo "paramfile= '"/glade/work/bmraczka/calLMIP/lhc/paramfiles/ctsm60_params.c251211.phen_mort.nc"'" >> ${fname}   
   echo "reseed_dead_plants = .false." >> ${fname}
   echo "clm_start_type = 'startup'"  >> ${fname}

#  Production run  initial conditions -- using midsummer starting point from tower free run
#  echo "finidat = '"/glade/derecho/scratch/bmraczka/archive/clm6_transient_precal/rest/1997-01-01-82800/clm6_transient_precal.clm2_${inst_string2}.r.1997-01-01-82800.nc"'"  >> ${fname}
  # echo "finidat = '"/glade/derecho/scratch/bmraczka/archive/clm6_tower_June/rest/1997-06-01-00000/clm6_tower_June.clm2_${inst_string2}.r.1997-06-01-00000.nc"'"  >> ${fname}
echo "finidat = '"/glade/derecho/scratch/bmraczka/archive/clm6_tower_June2010/rest/2010-06-01-00000/clm6_tower_June2010.clm2_${inst_string2}.r.2010-06-01-00000.nc"'"  >> ${fname}
#  echo "hist_fincl1 = 'FSIF','EFLX_LH_TOT'"        >> ${fname}
#  echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R'" >> ${fname}
#  echo "hist_nhtfrq = 0,-24"                       >> ${fname}
#  echo "hist_mfilt  = 1,31"                        >> ${fname}
#  echo "hist_avgflag_pertape = 'A','A'"            >> ${fname}
#  echo "hist_dov2xy = .true.,.true."               >> ${fname}
#  echo "hist_type1d_pertape = ' ',' '"             >> ${fname}




   @ inst ++
end

./preview_namelists || exit 6

# ==============================================================================
# Stage the restarts now that the run directory exists
# ==============================================================================

#echo "staging restarts"

set init_time = ${reftimestamp}

cat << EndOfText >! stage_cesm_files
#!/bin/csh -f
# This script can be used to help restart an experiment from any previous step.
# The appropriate files are copied to the RUN directory.
#
# Before running this script:
#  1) be sure CONTINUE_RUN is set correctly in the env_run.xml file in
#     your CASEROOT directory.
#     CONTINUE_RUN=FALSE => you are starting over at the initial time.
#     CONTINUE_RUN=TRUE  => you are starting from a previous step but not
#                           the very first one.
#  2) be sure 'restart_time' is set to the day and time that you want to
#     restart from if not the initial time.
#
#  3) be sure the prior inflation files are re-staged 
#     STAGE_INFLATION FALSE => no restage, default setting when case is first created
#     STAGE_INFLATION TRUE  => you are starting from a previous step or
#                              from the initial time            
#
#
#

set restart_time = $init_time
set STAGE_INFLATION = FALSE


# get the settings for this case from the CESM environment
cd ${caseroot}

setenv CONTINUE_RUN \`./xmlquery CONTINUE_RUN --value\`
setenv RUNDIR       \`./xmlquery RUNDIR       --value\`
setenv DOUT_S       \`./xmlquery DOUT_S       --value\`
setenv DOUT_S_ROOT  \`./xmlquery DOUT_S_ROOT  --value\`
setenv CASE         \`./xmlquery CASE         --value\`

cd \${RUNDIR}

echo 'Copying the required CESM files to the run directory to rerun'
echo 'a previous step.  CONTINUE_RUN from env_run.xml is' \${CONTINUE_RUN}
if ( \${CONTINUE_RUN} == TRUE ) then
  echo 'so files for some later step than the initial one will be restaged.'
  echo "Date to reset files to is: \${restart_time}"
else
  echo 'so files for the initial step of this experiment will be restaged.'
  echo "Date to reset files to is: ${init_time}"
endif
echo ''

if ( \${CONTINUE_RUN} == TRUE ) then

   #----------------------------------------------------------------------
   # This block copies over a set of restart files from any previous step of
   # the experiment that is NOT the initial step.
   # After running this script resubmit the job to rerun.
   #----------------------------------------------------------------------

   echo "Staging restart files for run date/time: " \${restart_time}

   #  The short term archiver is on, so the files we want should be in one
   #  of the short term archive 'rest' restart directories.  This assumes
   #  the long term archiver has NOT copied these files to the HPSS yet.

   if (  \${DOUT_S} == TRUE ) then

      # The restarts should be in the short term archive directory.

      set RESTARTDIR = \${DOUT_S_ROOT}/rest/\${restart_time}

      if ( ! -d \${RESTARTDIR} ) then

         echo "restart file directory not found: "
         echo " \${RESTARTDIR}"
         echo "If the long-term archiver is on, you may have to restore this directory first."
         echo "You can also check for either a .sta or a .sta2 hidden subdirectory in"
         echo "\${DOUT_S_ROOT}"
         echo "which may contain the 'rest' directory you need,"
         echo "and then modify RESTARTDIR in this script."
         exit 7

      endif

      ${COPY} \${RESTARTDIR}/* . || exit 7

   else

      # The short term archiver is off, which leaves all the restart files
      # in the run directory.  The rpointer files must still be updated to
      # point to the files with the right day/time.

      @ inst=1
      while (\$inst <= $num_instances)

         set inst_string = \`printf _%04d \$inst\`

         echo "\${CASE}.cpl\${inst_string}.r.\${restart_time}.nc"    >! rpointer.drv\${inst_string}
         echo "\${CASE}.clm2\${inst_string}.r.\${restart_time}.nc"   >! rpointer.lnd\${inst_string}
         echo "\${CASE}.datm\${inst_string}.r.\${restart_time}.nc"   >! rpointer.atm\${inst_string}
         echo "\${CASE}.datm\${inst_string}.rs1.\${restart_time}.nc" >> rpointer.atm\${inst_string}
         echo "\${CASE}.mosart\${inst_string}.r.\${restart_time}.nc" >! rpointer.rof\${inst_string}

         @ inst ++
      end

      # If the multi-driver is not being used,
      # there is only a single coupler restart file.
      echo "\${CASE}.cpl.r.\${restart_time}.nc" >! rpointer.drv

   endif

   echo "All files reset to rerun experiment step for time " \$restart_time

else     # CONTINUE_RUN == FALSE

   #----------------------------------------------------------------------
   # This block links the right files to rerun the initial (very first)
   # step of an experiment.  The names and locations are set during the
   # building of the case; to change them rebuild the case.
   # After running this script resubmit the job to rerun.
   #----------------------------------------------------------------------

   @ inst=1
   while (\$inst <= $num_instances)

      set inst_string = \`printf _%04d \$inst\`

      echo "Staging initial files for instance \$inst of $num_instances"

      if ( -e    ${stagedir}/${refcase}.clm2\${inst_string}.r.${init_time}.nc ) then
         ${LINK} ${stagedir}/${refcase}.clm2\${inst_string}.r.${init_time}.nc .
      else
         echo "ERROR: ${stagedir}/${refcase}.clm2\${inststring}.r.${init_time}.nc does not exist."
         echo "       Check your 'reftimestamp' setting, or maybe your 'stagedir' or 'refcase' or ..."
         exit 8
      endif

      if (-e     ${stagedir}/${refcase}.mosart\${inst_string}.r.${init_time}.nc ) then
         ${LINK} ${stagedir}/${refcase}.mosart\${inst_string}.r.${init_time}.nc .
      else
        echo "WARNING: ${stagedir}/${refcase}.mosart\${inst_string}.r.${init_time}.nc does not exist."
        echo "       Check your 'reftimestamp' setting, or maybe your 'stagedir' or 'refcase' or ..."
        echo "       If this is not a mistake, set finidat_rtm = ' ', within mosart namelist or input file"
      endif

      @ inst ++
   end

   echo "All files set to run the FIRST experiment step at time" $init_time

endif

   #----------------------------------------------------------------------
   # This block modifies the inflation rpointer files (priorinf_pointer_d{01-03}.txt)
   # such that the DART code uses the inflation files (clm_output_priorinf*.nc) from the 
   # previous time step (e.g. restart_time)
   # e.g. the following files:
   # clm_output_priorinf_mean_d01.2011-01-03-00000.nc
   # clm_output_priorinf_sd_d01.2011-01-03-00000.nc
   # would be used to apply inflation for time step: 2011-01-04
   #----------------------------------------------------------------------

if ( \${STAGE_INFLATION} == TRUE) then

# Confirm inflation is being used.

set  MYSTRING = \`grep inf_flavor input.nml\`
set  MYSTRING = \`echo \$MYSTRING | sed -e "s#[=,'\.]# #g"\`
set  PRIOR_INF = \$MYSTRING[2]
set  POSTE_INF = \$MYSTRING[3]

  if ( \$PRIOR_INF != 0 ) then

    if  ( \${CONTINUE_RUN} == FALSE) then
       # Generate cookie such that fill_inflation_restart 
       # generates inflation files

       date >! \${RUNDIR}/clm_inflation_cookie

    else  # CONTINUE_RUN=TRUE

         if ( ! -e priorinf_pointer_d01.txt ) then

         echo "ERROR: priorinf_pointer_d01.txt file not found"
         echo "At least 1 domain pointer file should exist if assimilation run is re-staged"
         echo "Prior inflation files will not be re-staged"
         exit 2

         endif

       @ domaincount = 0
       echo "     "
       echo "Re-setting priorinf pointer files for " \$restart_time
       echo "     "

     foreach POINTERFILE ( priorinf_pointer*.txt )

        @ domaincount ++

        set POINTERFILE = \`printf priorinf_pointer_d%02d.txt \$domaincount\`
        echo "Located inflation pointer file: " \$POINTERFILE
        set DOMAIN = \`printf _d%02d \$domaincount\`
        set FILE   = \`printf clm_output_priorinf_mean\${DOMAIN}.\${restart_time}.nc\`

         if ( ! -e \${FILE} ) then
         echo "ERROR: \${FILE} not found"
         echo "This file must exist to be inserted in \${POINTERFILE}"
         echo "Prior inflation file will not be re-staged"
         exit 3
         endif

        set SDFILE = \`echo \$FILE | sed -e "s#mean#sd#"\`
        echo "Inserting the prior inflation file into pointer: " \$FILE
        echo \$FILE   >! \$POINTERFILE
        echo \$SDFILE >> \$POINTERFILE

     end

     echo "The priorinf pointer files are reset to rerun experiment at: " \$restart_time
     echo "    "

    endif

  else   # \$PRIOR_INF==0

    echo "Warning: Prior inflation is turned off for this assimilation"
    echo "Inflation files will not be re-staged"
    echo "Check your input.nml inflation settings"

  endif

   if ( \$POSTE_INF != 0 ) then
      echo "ERROR: stage_cesm_files not configured to stage posterior inflation files."
      exit 4
   endif
endif

exit 0

EndOfText
chmod 0755 stage_cesm_files

#./stage_cesm_files || exit 8

#===============================================================================
# This example has SourceMods that enable CLM to output solar induced fluorescence
# as an additional diagnostic variable ("FSIF") in the history file.
# There are also SourceMods that suppress the balance checks for the first
# restart timestep.

if ( ${use_SourceMods} == TRUE ) then

   if (    -d    ${SourceModDir} ) then
      ${COPY} -r ${SourceModDir}/* ${caseroot}/SourceMods/ || exit 7

      if ( -e    SourceMods/src.clm ) then
         cd      SourceMods/src.clm
         ${LINK} `find . -name "*F90"` . || exit 7
         cd      ../..
      endif
   else
      echo "ERROR - DART_params.csh use_SourceMods = ${use_SourceMods}"
      echo "ERROR - but there are no SourceMods in ${SourceModDir}"
      echo "        See discussion in DART_params.csh for information on"
      echo "        where to get a tar file of SourceMods for DART." 
      exit 7
   endif
endif

./case.build || exit 7

# ==============================================================================
# Stage working copies of parameter ensemble files to RUNDIR.
#
# These are the per-member parameter files (one per ensemble member) that CLM
# reads at runtime and that dart_to_clm updates after each DA cycle.
# The originals in paramdir are NEVER modified -- only the working copies in
# RUNDIR are updated. If a working copy already exists it is left unchanged,
# so re-running this setup script after a partial copy is safe.
#
# Requires these variables from DART_params_tower_assim.csh:
#   estimate_params  : TRUE to stage param files, skip otherwise
#   paramdir         : directory containing the original ensemble param files
#   param_file_base  : base filename (e.g. calLMIP_precalibrated)
#   num_instances    : ensemble size (files numbered 0001 to num_instances)
# ==============================================================================

if ( $estimate_params == TRUE ) then

   if ( ! -d ${rundir} ) then
      echo "ERROR: RUNDIR ${rundir} does not exist after case.build."
      echo "       Cannot stage parameter files. Check build output above."
      exit 8
   endif

   echo "Staging parameter ensemble files to ${rundir} ..."

   @ inst = 1
   while ( $inst <= $num_instances )

      set PARAM_SRC  = `printf ${paramdir}/${param_file_base}%04d.nc $inst`
      set PARAM_DEST = `printf ${rundir}/${param_file_base}%04d.nc $inst`

      if ( ! -e $PARAM_SRC ) then
         echo "ERROR: Source param file not found: $PARAM_SRC"
         echo "       Check paramdir and param_file_base in DART_params_tower_assim.csh"
         exit 8
      endif

      if ( ! -e $PARAM_DEST ) then
         ${COPY} $PARAM_SRC $PARAM_DEST
      else
         echo "NOTE: $PARAM_DEST already exists -- skipping copy (safe to ignore)."
      endif

      @ inst ++
   end

   echo "Parameter staging complete: ${num_instances} file(s) staged to ${rundir}"

endif

# ==============================================================================
# What to do next
# ==============================================================================

cat << EndOfText >! CESM_instructions.txt

-------------------------------------------------------------------------
Time to check the case.

1) cd ${rundir}
   and check the compatibility between the namelists/pointer files
   and the files that were staged.

2) cd ${caseroot}

3) check things

4) run a single job (and send mail), verify that it works
   ./case.submit -M all

5) If that works
   ./xmlchange CONTINUE_RUN=TRUE
   that sort of thing
-------------------------------------------------------------------------

EndOfText

cat CESM_instructions.txt

exit 0

