#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../build_templates/mkmf -p id_set_def_stdin \
 -t  ../../../build_templates/mkmf.template -c"-Duse_netCDF" \
 -a "../../.." path_names_id_set_def_stdin

exit $status

