! Data Assimilation Research Testbed -- DART
! Copyright 2004-2007, Data Assimilation Research Section
! University Corporation for Atmospheric Research
! Licensed under the GPL -- www.gpl.org/licenses/gpl.html

! <next few lines under version control, do not edit>
! $URL$
! $Id$
! $Revision$
! $Date$

! BEGIN DART PREPROCESS KIND LIST
!BUOY_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!BUOY_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!BUOY_SURFACE_PRESSURE,        KIND_SURFACE_PRESSURE
!BUOY_TEMPERATURE,             KIND_TEMPERATURE
!BUOY_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!SHIP_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!SHIP_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!SHIP_SURFACE_PRESSURE,        KIND_SURFACE_PRESSURE
!SHIP_TEMPERATURE,             KIND_TEMPERATURE
!SHIP_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!SYNOP_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!SYNOP_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!SYNOP_SURFACE_PRESSURE,        KIND_SURFACE_PRESSURE
!SYNOP_TEMPERATURE,             KIND_TEMPERATURE
!SYNOP_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!AIREP_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!AIREP_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!AIREP_PRESSURE,                KIND_PRESSURE
!AIREP_TEMPERATURE,             KIND_TEMPERATURE
!AIREP_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!AMDAR_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!AMDAR_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!AMDAR_PRESSURE,                KIND_PRESSURE
!AMDAR_TEMPERATURE,             KIND_TEMPERATURE
!AMDAR_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!PILOT_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!PILOT_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!PILOT_PRESSURE,                KIND_PRESSURE
!PILOT_TEMPERATURE,             KIND_TEMPERATURE
!PILOT_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!BOGUS_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT
!BOGUS_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT
!BOGUS_PRESSURE,                KIND_PRESSURE
!BOGUS_TEMPERATURE,             KIND_TEMPERATURE
!BOGUS_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE
!PROFILER_U_WIND_COMPONENT,     KIND_U_WIND_COMPONENT
!PROFILER_V_WIND_COMPONENT,     KIND_V_WIND_COMPONENT
!PROFILER_PRESSURE,             KIND_PRESSURE
! END DART PREPROCESS KIND LIST

! BEGIN DART PREPROCESS USE OF SPECIAL OBS_DEF MODULE
!! No use statements are required for the reanalysis bufr obs_def module
! END DART PREPROCESS USE OF SPECIAL OBS_DEF MODULE

! BEGIN DART PREPROCESS GET_EXPECTED_OBS_FROM_DEF
!         case(BUOY_U_WIND_COMPONENT, SHIP_U_WIND_COMPONENT, &
!              SYNOP_U_WIND_COMPONENT, AIREP_U_WIND_COMPONENT, &
!              AMDAR_U_WIND_COMPONENT, PILOT_U_WIND_COMPONENT, &
!              PROFILER_U_WIND_COMPONENT, BOGUS_U_WIND_COMPONENT)
!            call interpolate(state, location, KIND_U_WIND_COMPONENT, obs_val, istatus)         
!         case(BUOY_V_WIND_COMPONENT, SHIP_V_WIND_COMPONENT, &
!              SYNOP_V_WIND_COMPONENT, AIREP_V_WIND_COMPONENT, &
!              AMDAR_V_WIND_COMPONENT, PILOT_V_WIND_COMPONENT, &
!              PROFILER_V_WIND_COMPONENT, BOGUS_V_WIND_COMPONENT)
!            call interpolate(state, location, KIND_V_WIND_COMPONENT, obs_val, istatus)         
!         case(BUOY_SURFACE_PRESSURE, SHIP_SURFACE_PRESSURE, &
!              SYNOP_SURFACE_PRESSURE, AIREP_PRESSURE, &
!              AMDAR_PRESSURE, PILOT_PRESSURE, &
!              PROFILER_PRESSURE, BOGUS_PRESSURE)
!            call interpolate(state, location, KIND_PRESSURE, obs_val, istatus)         
!         case(BUOY_TEMPERATURE, SHIP_TEMPERATURE, &
!              SYNOP_TEMPERATURE, AIREP_TEMPERATURE, &
!              AMDAR_TEMPERATURE, PILOT_TEMPERATURE, BOGUS_TEMPERATURE)
!            call interpolate(state, location, KIND_TEMPERATURE, obs_val, istatus)         
!         case(BUOY_DEW_POINT_TEMPERATURE, SHIP_DEW_POINT_TEMPERATURE, &
!              SYNOP_DEW_POINT_TEMPERATURE, AIREP_DEW_POINT_TEMPERATURE, &
!              AMDAR_DEW_POINT_TEMPERATURE, PILOT_DEW_POINT_TEMPERATURE, &
!              BOGUS_DEW_POINT_TEMPERATURE)
!            call interpolate(state, location, KIND_TEMPERATURE, obs_val, istatus)         
! END DART PREPROCESS GET_EXPECTED_OBS_FROM_DEF

! BEGIN DART PREPROCESS READ_OBS_DEF
!case(BUOY_U_WIND_COMPONENT, BUOY_V_WIND_COMPONENT, BUOY_SURFACE_PRESSURE, &
!   BUOY_TEMPERATURE, BUOY_DEW_POINT_TEMPERATURE, &
!   SHIP_U_WIND_COMPONENT, SHIP_V_WIND_COMPONENT, SHIP_SURFACE_PRESSURE, &
!   SHIP_TEMPERATURE, SHIP_DEW_POINT_TEMPERATURE, &
!   SYNOP_U_WIND_COMPONENT, SYNOP_V_WIND_COMPONENT, SYNOP_SURFACE_PRESSURE, &
!   SYNOP_TEMPERATURE, SYNOP_DEW_POINT_TEMPERATURE, &
!   AIREP_U_WIND_COMPONENT, AIREP_V_WIND_COMPONENT, AIREP_PRESSURE, &
!   AIREP_TEMPERATURE, AIREP_DEW_POINT_TEMPERATURE, &
!   AMDAR_U_WIND_COMPONENT, AMDAR_V_WIND_COMPONENT, AMDAR_PRESSURE, &
!   AMDAR_TEMPERATURE, AMDAR_DEW_POINT_TEMPERATURE,& 
!   PILOT_U_WIND_COMPONENT, PILOT_V_WIND_COMPONENT, PILOT_PRESSURE, &
!   PILOT_TEMPERATURE, PILOT_DEW_POINT_TEMPERATURE, &
!   BOGUS_U_WIND_COMPONENT, BOGUS_V_WIND_COMPONENT, BOGUS_PRESSURE, &
!   BOGUS_TEMPERATURE, BOGUS_DEW_POINT_TEMPERATURE, &
!   PROFILER_U_WIND_COMPONENT, PROFILER_V_WIND_COMPONENT, PROFILER_PRESSURE )
!      continue
! END DART PREPROCESS READ_OBS_DEF

! BEGIN DART PREPROCESS WRITE_OBS_DEF
!case(BUOY_U_WIND_COMPONENT, BUOY_V_WIND_COMPONENT, BUOY_SURFACE_PRESSURE, &
!   BUOY_TEMPERATURE, BUOY_DEW_POINT_TEMPERATURE, &
!   SHIP_U_WIND_COMPONENT, SHIP_V_WIND_COMPONENT, SHIP_SURFACE_PRESSURE, &
!   SHIP_TEMPERATURE, SHIP_DEW_POINT_TEMPERATURE, &
!   SYNOP_U_WIND_COMPONENT, SYNOP_V_WIND_COMPONENT, SYNOP_SURFACE_PRESSURE, &
!   SYNOP_TEMPERATURE, SYNOP_DEW_POINT_TEMPERATURE, &
!   AIREP_U_WIND_COMPONENT, AIREP_V_WIND_COMPONENT, AIREP_PRESSURE, &
!   AIREP_TEMPERATURE, AIREP_DEW_POINT_TEMPERATURE, &
!   AMDAR_U_WIND_COMPONENT, AMDAR_V_WIND_COMPONENT, AMDAR_PRESSURE, &
!   AMDAR_TEMPERATURE, AMDAR_DEW_POINT_TEMPERATURE,& 
!   PILOT_U_WIND_COMPONENT, PILOT_V_WIND_COMPONENT, PILOT_PRESSURE, &
!   PILOT_TEMPERATURE, PILOT_DEW_POINT_TEMPERATURE, &
!   BOGUS_U_WIND_COMPONENT, BOGUS_V_WIND_COMPONENT, BOGUS_PRESSURE, &
!   BOGUS_TEMPERATURE, BOGUS_DEW_POINT_TEMPERATURE, &
!   PROFILER_U_WIND_COMPONENT, PROFILER_V_WIND_COMPONENT, PROFILER_PRESSURE )
!      continue
! END DART PREPROCESS WRITE_OBS_DEF

! BEGIN DART PREPROCESS INTERACTIVE_OBS_DEF
!case(BUOY_U_WIND_COMPONENT, BUOY_V_WIND_COMPONENT, BUOY_SURFACE_PRESSURE, &
!   BUOY_TEMPERATURE, BUOY_DEW_POINT_TEMPERATURE, &
!   SHIP_U_WIND_COMPONENT, SHIP_V_WIND_COMPONENT, SHIP_SURFACE_PRESSURE, &
!   SHIP_TEMPERATURE, SHIP_DEW_POINT_TEMPERATURE, &
!   SYNOP_U_WIND_COMPONENT, SYNOP_V_WIND_COMPONENT, SYNOP_SURFACE_PRESSURE, &
!   SYNOP_TEMPERATURE, SYNOP_DEW_POINT_TEMPERATURE, &
!   AIREP_U_WIND_COMPONENT, AIREP_V_WIND_COMPONENT, AIREP_PRESSURE, &
!   AIREP_TEMPERATURE, AIREP_DEW_POINT_TEMPERATURE, &
!   AMDAR_U_WIND_COMPONENT, AMDAR_V_WIND_COMPONENT, AMDAR_PRESSURE, &
!   AMDAR_TEMPERATURE, AMDAR_DEW_POINT_TEMPERATURE,& 
!   PILOT_U_WIND_COMPONENT, PILOT_V_WIND_COMPONENT, PILOT_PRESSURE, &
!   PILOT_TEMPERATURE, PILOT_DEW_POINT_TEMPERATURE, &
!   BOGUS_U_WIND_COMPONENT, BOGUS_V_WIND_COMPONENT, BOGUS_PRESSURE, &
!   BOGUS_TEMPERATURE, BOGUS_DEW_POINT_TEMPERATURE, &
!   PROFILER_U_WIND_COMPONENT, PROFILER_V_WIND_COMPONENT, PROFILER_PRESSURE )
!      continue
! END DART PREPROCESS INTERACTIVE_OBS_DEF

