! Data Assimilation Research Testbed -- DART
! Copyright 2004-2007, Data Assimilation Research Section
! University Corporation for Atmospheric Research
! Licensed under the GPL -- www.gpl.org/licenses/gpl.html

! <next few lines under version control, do not edit>
! $URL$
! $Id$
! $Revision$
! $Date$

! BEGIN DART PREPROCESS KIND LIST
!BUOY_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT,       COMMON_CODE
!BUOY_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT,       COMMON_CODE
!BUOY_SURFACE_PRESSURE,        KIND_SURFACE_PRESSURE,       COMMON_CODE
!BUOY_TEMPERATURE,             KIND_TEMPERATURE,            COMMON_CODE
!BUOY_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE,  COMMON_CODE
!SHIP_U_WIND_COMPONENT,        KIND_U_WIND_COMPONENT,       COMMON_CODE
!SHIP_V_WIND_COMPONENT,        KIND_V_WIND_COMPONENT,       COMMON_CODE
!SHIP_SURFACE_PRESSURE,        KIND_SURFACE_PRESSURE,       COMMON_CODE
!SHIP_TEMPERATURE,             KIND_TEMPERATURE,            COMMON_CODE
!SHIP_DEW_POINT_TEMPERATURE,   KIND_DEW_POINT_TEMPERATURE,  COMMON_CODE
!SYNOP_U_WIND_COMPONENT,       KIND_U_WIND_COMPONENT,      COMMON_CODE
!SYNOP_V_WIND_COMPONENT,       KIND_V_WIND_COMPONENT,      COMMON_CODE
!SYNOP_SURFACE_PRESSURE,       KIND_SURFACE_PRESSURE,      COMMON_CODE
!SYNOP_TEMPERATURE,            KIND_TEMPERATURE,           COMMON_CODE
!SYNOP_DEW_POINT_TEMPERATURE,  KIND_DEW_POINT_TEMPERATURE, COMMON_CODE
!AIREP_U_WIND_COMPONENT,       KIND_U_WIND_COMPONENT,      COMMON_CODE
!AIREP_V_WIND_COMPONENT,       KIND_V_WIND_COMPONENT,      COMMON_CODE
!AIREP_PRESSURE,               KIND_PRESSURE,              COMMON_CODE
!AIREP_TEMPERATURE,            KIND_TEMPERATURE,           COMMON_CODE
!AIREP_DEW_POINT_TEMPERATURE,  KIND_DEW_POINT_TEMPERATURE, COMMON_CODE
!AMDAR_U_WIND_COMPONENT,       KIND_U_WIND_COMPONENT,      COMMON_CODE
!AMDAR_V_WIND_COMPONENT,       KIND_V_WIND_COMPONENT,      COMMON_CODE
!AMDAR_PRESSURE,               KIND_PRESSURE,              COMMON_CODE
!AMDAR_TEMPERATURE,            KIND_TEMPERATURE,           COMMON_CODE
!AMDAR_DEW_POINT_TEMPERATURE,  KIND_DEW_POINT_TEMPERATURE, COMMON_CODE
!PILOT_U_WIND_COMPONENT,       KIND_U_WIND_COMPONENT,      COMMON_CODE
!PILOT_V_WIND_COMPONENT,       KIND_V_WIND_COMPONENT,      COMMON_CODE
!PILOT_PRESSURE,               KIND_PRESSURE,              COMMON_CODE
!PILOT_TEMPERATURE,            KIND_TEMPERATURE,           COMMON_CODE
!PILOT_DEW_POINT_TEMPERATURE,  KIND_DEW_POINT_TEMPERATURE, COMMON_CODE
!BOGUS_U_WIND_COMPONENT,       KIND_U_WIND_COMPONENT,      COMMON_CODE
!BOGUS_V_WIND_COMPONENT,       KIND_V_WIND_COMPONENT,      COMMON_CODE
!BOGUS_PRESSURE,               KIND_PRESSURE,              COMMON_CODE
!BOGUS_TEMPERATURE,            KIND_TEMPERATURE,           COMMON_CODE
!BOGUS_DEW_POINT_TEMPERATURE,  KIND_DEW_POINT_TEMPERATURE, COMMON_CODE
!PROFILER_U_WIND_COMPONENT,    KIND_U_WIND_COMPONENT,      COMMON_CODE
!PROFILER_V_WIND_COMPONENT,    KIND_V_WIND_COMPONENT,      COMMON_CODE
!PROFILER_PRESSURE,            KIND_PRESSURE,              COMMON_CODE
! END DART PREPROCESS KIND LIST

