#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id$
#
# usage: mkmf_perfect_model_obs [ -mpi | -nompi ]
#
# without any args, builds perfect_model_obs without mpi libraries, and it will run
# as a normal executable. if -mpi is given, it will be compiled with the mpi
# libraries and can run with multiple cooperating processes.

if ( $#argv > 0 ) then
  if ("$argv[1]" == "-mpi") then
    setenv usingmpi 1
  else if ("$argv[1]" == "-nompi") then
    setenv usingmpi 0
  else
    echo "Unrecognized argument to mkmf_perfect_model_obs: $argv[1]"
    echo "Usage: mkmf_perfect_model_obs [ -mpi | -nompi ]"
    echo " default is to generate a Makefile without MPI support."
    exit -1
  endif
else
  setenv usingmpi 0
endif

set XTRALIBS_BASE = /glade/scratch/jsteward/RTTOV/

set JPGDIR = /glade/scratch/jsteward/DART_dev_radiance/observations/obs_converters/AIRS/HDF-EOS2/hdfeos/hdfeos2
set HDFDIR = /glade/u/apps/ch/opt/netcdf/4.7.1/intel/18.0.5/
set EOSDIR = /glade/u/apps/ch/opt/hdf/4.2.14/intel/18.0.5/
set RTTOV = ${XTRALIBS_BASE}

set JPGINC = ${JPGDIR}/include
set JPGLIB = ${JPGDIR}/lib

set HDFINC = ${HDFDIR}/include
set HDFLIB = ${HDFDIR}/lib

set EOSINC = ${EOSDIR}/include
set EOSLIB = ${EOSDIR}/lib

set RTINC = "${RTTOV}/include"
set RTMOD = "${RTTOV}/mod"
set RTLIB = "${RTTOV}/lib"
set RTLIBS = "-lrttov12_wrapper -lrttov12_mw_scatt -lrttov12_brdf_atlas -lrttov12_emis_atlas -lrttov12_other -lrttov12_parallel -lrttov12_coef_io -lrttov12_hdf -lrttov12_main -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5"

# leaving this out for now: rttov_parallel

set MYLIBS = "${RTLIBS} -lhdfeos -lmfhdf -ldf -ljpeg -lz  -lm"

set MYINCDIRS = "-I${RTINC} -I${RTMOD} -I${EOSINC} -I${HDFINC} -I${JPGINC}"
set MYLIBDIRS = "-L${RTLIB} -L${EOSLIB} -L${HDFLIB} -L${JPGLIB}"

# is -cpp compiler specific?  on a mac with a case-insensitive filesystem
# we have to tell it to call cpp to build files with #if and #include lines.

set MYFLAGS = "-cpp ${MYINCDIRS}"


# make a backup copy of the path_names file, and then use
# sed to make sure it includes either the non-mpi subroutines,
# or the subroutines which really call mpi.
cp -f path_names_perfect_model_obs path_names_perfect_model_obs.back

if ( $usingmpi ) then

  echo "Making Makefile with MPI"
  touch using_mpi_for_perfect_model_obs
  sed -e 's#/null_mpi_util#/mpi_util#' \
      -e 's#/null_win_mod#/no_cray_win_mod#' path_names_perfect_model_obs.back >! path_names_perfect_model_obs

  setenv wrapper_arg -w

else

  echo "Making Makefile without MPI"
  rm -f using_mpi_for_perfect_model_obs
  sed -e 's#/mpi_util#/null_mpi_util#' \
      -e '\#no_cray_win_mod.f90#d' \
      -e '\#cray_win_mod.f90#d' path_names_perfect_model_obs.back >! path_names_perfect_model_obs

  set p=`grep null_win_mod.f90 path_names_perfect_model_obs | wc -w`
  if ( $p == 0) then
     echo assimilation_code/modules/utilities/null_win_mod.f90 >> path_names_perfect_model_obs
  endif

  setenv wrapper_arg ""

endif

# remove temp file and now really call mkmf to generate makefile
rm -f path_names_perfect_model_obs.back

../../../build_templates/mkmf -p perfect_model_obs -t ../../../build_templates/mkmf.template \
 -o "${MYFLAGS}" -l "${MYFLAGS} ${MYINCDIRS} ${MYLIBDIRS} ${MYLIBS}" \
 -a "../../.." ${wrapper_arg} path_names_perfect_model_obs

exit $status

# <next few lines under version control, do not edit>
# $URL$
# $Revision$
# $Date$

