! DART software - Copyright UCAR. This open source software is provided
! by UCAR, "as is", without charge, subject to all terms of use at
! http://www.image.ucar.edu/DAReS/DART/DART_download

! ! in this section, define the quantity of interest.  it must
! ! start with QTY_xxx and be less than 32 characters total.
! ! if there are units, min/max values, pdf, etc you can add one or
! ! more name=value pairs.  at this point there *cannot* be spaces
! ! around the equals sign.  the value can have spaces if it is
! ! surrounded by double quotes.  e.g. desc="assumes dry air density"
! ! comment lines (like these) can be added if they start with an additional !

!
! BEGIN DART PREPROCESS QUANTITY DEFINITIONS
!
! ! kinds for CICE
!
!   QTY_SEAICE_AGREG_CONCENTR
!   QTY_SEAICE_AGREG_FREEBOARD
!   QTY_SEAICE_AGREG_VOLUME
!   QTY_SEAICE_AGREG_SNOWVOLUME
!   QTY_SEAICE_AGREG_THICKNESS
!   QTY_SEAICE_AGREG_SNOWDEPTH
!   QTY_U_SEAICE_COMPONENT
!   QTY_V_SEAICE_COMPONENT
!   QTY_SEAICE_ALBEDODIRVIZ
!   QTY_SEAICE_ALBEDODIRNIR
!   QTY_SEAICE_ALBEDOINDVIZ
!   QTY_SEAICE_ALBEDOINDNIR
!   QTY_SEAICE_CATEGORY
!   QTY_SEAICE_CONCENTR
!   QTY_SEAICE_VOLUME
!   QTY_SEAICE_SNOWVOLUME
!   QTY_SEAICE_SURFACETEMP
!   QTY_SEAICE_FIRSTYEARAREA
!   QTY_SEAICE_ICEAGE
!   QTY_SEAICE_LEVELAREA
!   QTY_SEAICE_LEVELVOLUME
!   QTY_SEAICE_MELTPONDAREA
!   QTY_SEAICE_MELTPONDDEPTH
!   QTY_SEAICE_MELTPONDLID
!   QTY_SEAICE_MELTPONDSNOW
!   QTY_SEAICE_SALINITY001
!   QTY_SEAICE_SALINITY002
!   QTY_SEAICE_SALINITY003
!   QTY_SEAICE_SALINITY004
!   QTY_SEAICE_SALINITY005
!   QTY_SEAICE_SALINITY006
!   QTY_SEAICE_SALINITY007
!   QTY_SEAICE_SALINITY008
!   QTY_SEAICE_ICEENTHALPY001
!   QTY_SEAICE_ICEENTHALPY002
!   QTY_SEAICE_ICEENTHALPY003
!   QTY_SEAICE_ICEENTHALPY004
!   QTY_SEAICE_ICEENTHALPY005
!   QTY_SEAICE_ICEENTHALPY006
!   QTY_SEAICE_ICEENTHALPY007
!   QTY_SEAICE_ICEENTHALPY008
!   QTY_SEAICE_SNOWENTHALPY001
!   QTY_SEAICE_SNOWENTHALPY002
!   QTY_SEAICE_SNOWENTHALPY003
!   QTY_SOM_TEMPERATURE
!   QTY_SEAICE_FY
!   QTY_SEAICE_AGREG_FY
!   QTY_SEAICE_AGREG_SURFACETEMP
!
! END DART PREPROCESS QUANTITY DEFINITIONS

