name: Build and run mpi init with ifx NCAR HPC Container
on:
  workflow_dispatch:
  push:
    branches:
      - cirrus_actions

jobs:
  # Job 1
  ifx-mpi-init:
    # Runner instance OS

    runs-on:
      group: cirrus-4x8

    # The 'ncarcisl' containers initialize their software environment 
    # through 'sourcing' a common configuration file (/container/config_env.sh). 
    # This is done by starting a bash *login* shell (bash -l [...])
    defaults:
      run:
        shell: bash -elo pipefail {0}

    # Deploy container on top of runner instance
    container:
      image: ncarcisl/hpcdev-x86_64:almalinux9-oneapi-mpich-latest

    steps:
      - name: Create mpi init program
        run: |
          echo 'program mpi_inits' > mpi_inits.f90
          echo '  use mpi, only: MPI_Init, MPI_Finalize' >> mpi_inits.f90
          echo '  implicit none' >> mpi_inits.f90
          echo '  integer :: ierr' >> mpi_inits.f90
          echo '  call MPI_Init(ierr)' >> mpi_inits.f90
          echo '  print *, "Hello, World!"' >> mpi_inits.f90
          echo '  call MPI_Finalize(ierr)' >> mpi_inits.f90
          echo 'end program mpi_inits' >> mpi_inits.f90

      - name: Compile program with ifx
        run: |
          source "/container/config_env.sh"
          which mpif90
          mpif90 -o mpi_init_ifx mpi_inits.f90

      - name: Run hello world program with ifx
        run: |
          which mpiexec
          mpiexec -n 1 ./mpi_init_ifx
