name: Pytools Tests

on:
  push:
    paths:
      - 'pytools/**'
  pull_request:
    paths:
      - 'pytools/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          pip install pytest
          cd pytools
          pip install -r pyDART.txt
      - name: Run pytest
        run: |
          cd pytools
          pytest
