#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../../build_templates/mkmf -p tropomi_no2_ascii_to_obs \
 -t  ../../../../build_templates/mkmf.template \
 -a "../../../.." path_names_maxdoas_no2_ascii_to_obs

exit $status

